#pragma line 1 "fully_connected/solution1/fc.c" ::: -10
#pragma line 1 "fully_connected/solution1/fc.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 149 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/opt/Xilinx/Vivado/2017.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 1
#pragma line 296 "/opt/Xilinx/Vivado/2017.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 2
#pragma line 7 "<command line>" 2 ::: 118
#pragma line 1 "<built-in>" 2 ::: 119
#pragma line 1 "fully_connected/solution1/fc.c" 2 ::: 120
#pragma line 1 "/home/sergiu/git/lic/hls/workspace/fully_connected/headers/defines.h" 1 ::: 121
#pragma line 2 "fully_connected/solution1/fc.c" 2 ::: 122
#pragma line 1 "/home/sergiu/git/lic/hls/workspace/fully_connected/headers/activations.h" 1 ::: 123
#pragma line 3 "fully_connected/solution1/fc.c" 2 ::: 131
