#pragma line 1 "fully_connected/solution1/fc.c" ::: 0
#pragma line 1 "fully_connected/solution1/fc.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 149 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/opt/Xilinx/Vivado/2017.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 11
#pragma line 296 "/opt/Xilinx/Vivado/2017.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 12
#pragma line 7 "<command line>" 2 ::: 128
#pragma line 1 "<built-in>" 2 ::: 129
#pragma line 1 "fully_connected/solution1/fc.c" 2 ::: 130
#pragma line 1 "/home/sergiu/git/lic/hls/workspace/fully_connected/headers/defines.h" 1 ::: 131
#pragma line 2 "fully_connected/solution1/fc.c" 2 ::: 132
#pragma line 1 "/home/sergiu/git/lic/hls/workspace/fully_connected/headers/activations.h" 1 ::: 133
#pragma line 3 "fully_connected/solution1/fc.c" 2 ::: 141
