lappend pragmaStatus0 {pragma "DATAFLOW" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "nnet" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "conv_layer1/conv_layer1_label6" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus2 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "conv_layer1/conv_layer1_label7" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "conv_layer1/conv_layer1_label8" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "conv_layer1/conv_layer1_label2" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "conv_layer1/conv_layer1_label9" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus6 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "conv_layer2/conv_layer2_label10" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus7 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "conv_layer2/conv_layer2_label11" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus8 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "conv_layer2/conv_layer2_label12" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus9 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "conv_layer2/conv_layer2_label13" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus10 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "conv_layer2/conv_layer2_label4" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus11 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "conv_layer2/conv_layer2_label3" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus12 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "conv_layer1/conv_layer1_label0" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus13 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "conv_layer1/conv_layer1_label1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus14 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer1/pool_layer1_label14" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus15 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer1/pool_layer1_label15" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus16 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer1/pool_layer1_label16" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus17 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer1/pool_layer1_label17" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Label 'pool_layer1_label17' does not exist in function 'pool_layer1'. "}
lappend pragmaStatus18 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer1/pool_layer1_label18" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus19 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer1/pool_layer1_label19" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus20 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer1/pool_layer1_label20" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus21 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer1/pool_layer1_label21" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Label 'pool_layer1_label21' does not exist in function 'pool_layer1'. "}
lappend pragmaStatus22 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer1/pool_layer1_label6" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus23 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer1/pool_layer1_label22" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Label 'pool_layer1_label22' does not exist in function 'pool_layer1'. "}
lappend pragmaStatus24 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer1/pool_layer1_label23" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Label 'pool_layer1_label23' does not exist in function 'pool_layer1'. "}
lappend pragmaStatus25 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer1/pool_layer1_label7" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus26 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer2/pool_layer2_label24" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Label 'pool_layer2_label24' does not exist in function 'pool_layer2'. "}
lappend pragmaStatus27 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer2/pool_layer2_label25" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Label 'pool_layer2_label25' does not exist in function 'pool_layer2'. "}
lappend pragmaStatus28 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer2/pool_layer2_label26" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus29 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer2/pool_layer2_label27" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Label 'pool_layer2_label27' does not exist in function 'pool_layer2'. "}
lappend pragmaStatus30 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer2/pool_layer2_label8" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Label 'pool_layer2_label8' does not exist in function 'pool_layer2'. "}
lappend pragmaStatus31 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer2/pool_layer2_label29" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Label 'pool_layer2_label29' does not exist in function 'pool_layer2'. "}
lappend pragmaStatus32 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer2/pool_layer2_label16" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus33 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer2/pool_layer2_label9" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus34 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "fc_layer1/fc_layer1_label30" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Label 'fc_layer1_label30' does not exist in function 'fc_layer1'. "}
lappend pragmaStatus35 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "fc_layer1/fc_layer1_label12" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus36 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "fc_layer2/fc_layer2_label31" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Label 'fc_layer2_label31' does not exist in function 'fc_layer2'. "}
lappend pragmaStatus37 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "fc_layer2/fc_layer2_label13" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus38 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "fc_layer3/fc_layer3_label32" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Label 'fc_layer3_label32' does not exist in function 'fc_layer3'. "}
lappend pragmaStatus39 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "fc_layer3/fc_layer3_label10" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus40 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer1/pool_layer1_label33" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus41 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer1/pool_layer1_label34" found 0 funcFound 1 applied 0 ambiguous 0 reason "Directive 'UNROLL' cannot be applied: Label 'pool_layer1_label34' does not exist in function 'pool_layer1'. "}
lappend pragmaStatus42 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer1/pool_layer1_label35" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus43 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer2/pool_layer2_label36" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus44 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer2/pool_layer2_label37" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus45 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer2/pool_layer2_label38" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus46 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer2/pool_layer2_label39" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus47 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "fc_layer1/fc_layer1_label40" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus48 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "fc_layer2/fc_layer2_label41" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus49 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "fc_layer3/fc_layer3_label42" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus50 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer2/pool_layer2_label0" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus51 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer2/pool_layer2_label28" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus52 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::cos_K2' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::cos_K2"}
lappend pragmaStatus53 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::cos_K4' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::cos_K4"}
lappend pragmaStatus54 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::cos_K2' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::cos_K2"}
lappend pragmaStatus55 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'first_order_fixed_16::sin_cos_K1' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "first_order_fixed_16::sin_cos_K1"}
lappend pragmaStatus56 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_K3' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::sin_K3"}
lappend pragmaStatus57 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::cos_K1' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::cos_K1"}
lappend pragmaStatus58 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::cos_K0' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::cos_K0"}
lappend pragmaStatus59 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_cos_K2' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "second_order_float::sin_cos_K2"}
lappend pragmaStatus60 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'first_order_fixed_16::sin_cos_K0' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "first_order_fixed_16::sin_cos_K0"}
lappend pragmaStatus61 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_K1' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::sin_K1"}
lappend pragmaStatus62 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_cos_K4' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "fourth_order_double::sin_cos_K4"}
lappend pragmaStatus63 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::cos_K0' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::cos_K0"}
lappend pragmaStatus64 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::cos_K1' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::cos_K1"}
lappend pragmaStatus65 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_cos_K0' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "second_order_float::sin_cos_K0"}
lappend pragmaStatus66 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_K0' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::sin_K0"}
lappend pragmaStatus67 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_cos_K1' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "second_order_float::sin_cos_K1"}
lappend pragmaStatus68 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_K2' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::sin_K2"}
lappend pragmaStatus69 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_cos_K0' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "fourth_order_double::sin_cos_K0"}
lappend pragmaStatus70 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_cos_K1' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "fourth_order_double::sin_cos_K1"}
lappend pragmaStatus71 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_cos_K2' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "fourth_order_double::sin_cos_K2"}
lappend pragmaStatus72 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_K1' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::sin_K1"}
lappend pragmaStatus73 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_cos_K3' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "fourth_order_double::sin_cos_K3"}
lappend pragmaStatus74 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_K2' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::sin_K2"}
lappend pragmaStatus75 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_K0' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::sin_K0"}
lappend pragmaStatus76 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::cos_K3' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::cos_K3"}
lappend pragmaStatus77 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_K4' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::sin_K4"}
