lappend pragmaStatus0 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "conv_layer1/conv_layer1_label0" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "conv_layer1/conv_layer1_label1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus2 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "conv_layer1/conv_layer1_label2" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "conv_layer2/conv_layer2_label3" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "conv_layer2/conv_layer2_label4" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "conv_layer2/conv_layer2_label5" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus6 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer1/pool_layer1_label6" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus7 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer1/pool_layer1_label7" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus8 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer2/pool_layer2_label8" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus9 {pragma "PROTOCOL" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer2/pool_layer2_label9" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus10 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "fc_layer3/fc_layer3_label10" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus11 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "fc_layer2/fc_layer2_label11" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus12 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "fc_layer1/fc_layer1_label12" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus13 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "fc_layer2/fc_layer2_label13" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus14 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "fc_layer3/fc_layer3_label14" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus15 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "fc_layer1/fc_layer1_label15" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus16 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "pool_layer2/pool_layer2_label16" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus17 {pragma "DATAFLOW" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "nnet" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus18 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::cos_K2' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::cos_K2"}
lappend pragmaStatus19 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::cos_K4' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::cos_K4"}
lappend pragmaStatus20 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::cos_K2' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::cos_K2"}
lappend pragmaStatus21 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'first_order_fixed_16::sin_cos_K1' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "first_order_fixed_16::sin_cos_K1"}
lappend pragmaStatus22 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_K3' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::sin_K3"}
lappend pragmaStatus23 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::cos_K1' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::cos_K1"}
lappend pragmaStatus24 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::cos_K0' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::cos_K0"}
lappend pragmaStatus25 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_cos_K2' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "second_order_float::sin_cos_K2"}
lappend pragmaStatus26 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'first_order_fixed_16::sin_cos_K0' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "first_order_fixed_16::sin_cos_K0"}
lappend pragmaStatus27 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_K1' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::sin_K1"}
lappend pragmaStatus28 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_cos_K4' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "fourth_order_double::sin_cos_K4"}
lappend pragmaStatus29 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::cos_K0' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::cos_K0"}
lappend pragmaStatus30 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::cos_K1' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::cos_K1"}
lappend pragmaStatus31 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_cos_K0' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "second_order_float::sin_cos_K0"}
lappend pragmaStatus32 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_K0' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::sin_K0"}
lappend pragmaStatus33 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_cos_K1' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "second_order_float::sin_cos_K1"}
lappend pragmaStatus34 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_K2' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::sin_K2"}
lappend pragmaStatus35 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_cos_K0' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "fourth_order_double::sin_cos_K0"}
lappend pragmaStatus36 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_cos_K1' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "fourth_order_double::sin_cos_K1"}
lappend pragmaStatus37 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_cos_K2' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "fourth_order_double::sin_cos_K2"}
lappend pragmaStatus38 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_K1' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::sin_K1"}
lappend pragmaStatus39 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_cos_K3' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "fourth_order_double::sin_cos_K3"}
lappend pragmaStatus40 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_K2' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::sin_K2"}
lappend pragmaStatus41 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_K0' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::sin_K0"}
lappend pragmaStatus42 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::cos_K3' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::cos_K3"}
lappend pragmaStatus43 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/nnet_stream/solution1/nnet.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_K4' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::sin_K4"}
