// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __conv_layer2_conv_efO_H__
#define __conv_layer2_conv_efO_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct conv_layer2_conv_efO_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 11;
  static const unsigned AddressRange = 16;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(conv_layer2_conv_efO_ram) {
        ram[0] = "0b00100000101";
        ram[1] = "0b01010110001";
        ram[2] = "0b01011011000";
        ram[3] = "0b00000111000";
        ram[4] = "0b11010001001";
        ram[5] = "0b00110011010";
        ram[6] = "0b00111111101";
        ram[7] = "0b11011110100";
        ram[8] = "0b01011000001";
        ram[9] = "0b11011110000";
        ram[10] = "0b11000001110";
        ram[11] = "0b01001010110";
        ram[12] = "0b11100110110";
        ram[13] = "0b00001001110";
        ram[14] = "0b00101101010";
        ram[15] = "0b00101111101";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(conv_layer2_conv_efO) {


static const unsigned DataWidth = 11;
static const unsigned AddressRange = 16;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


conv_layer2_conv_efO_ram* meminst;


SC_CTOR(conv_layer2_conv_efO) {
meminst = new conv_layer2_conv_efO_ram("conv_layer2_conv_efO_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~conv_layer2_conv_efO() {
    delete meminst;
}


};//endmodule
#endif
