// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __conv_layer2_conv_eoQ_H__
#define __conv_layer2_conv_eoQ_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct conv_layer2_conv_eoQ_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 11;
  static const unsigned AddressRange = 16;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(conv_layer2_conv_eoQ_ram) {
        ram[0] = "0b01100111101";
        ram[1] = "0b10000100110";
        ram[2] = "0b00111000110";
        ram[3] = "0b00111100001";
        ram[4] = "0b10011000100";
        ram[5] = "0b01011010001";
        ram[6] = "0b00110111010";
        ram[7] = "0b10010101010";
        ram[8] = "0b11010110100";
        ram[9] = "0b11011010101";
        ram[10] = "0b00010100010";
        ram[11] = "0b01111000110";
        ram[12] = "0b00110011110";
        ram[13] = "0b11000011000";
        ram[14] = "0b10001101111";
        ram[15] = "0b01110010000";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(conv_layer2_conv_eoQ) {


static const unsigned DataWidth = 11;
static const unsigned AddressRange = 16;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


conv_layer2_conv_eoQ_ram* meminst;


SC_CTOR(conv_layer2_conv_eoQ) {
meminst = new conv_layer2_conv_eoQ_ram("conv_layer2_conv_eoQ_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~conv_layer2_conv_eoQ() {
    delete meminst;
}


};//endmodule
#endif
