// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "fc_layer3.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic fc_layer3::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic fc_layer3::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> fc_layer3::ap_ST_fsm_state1 = "1";
const sc_lv<9> fc_layer3::ap_ST_fsm_state2 = "10";
const sc_lv<9> fc_layer3::ap_ST_fsm_state3 = "100";
const sc_lv<9> fc_layer3::ap_ST_fsm_state4 = "1000";
const sc_lv<9> fc_layer3::ap_ST_fsm_state5 = "10000";
const sc_lv<9> fc_layer3::ap_ST_fsm_state6 = "100000";
const sc_lv<9> fc_layer3::ap_ST_fsm_state7 = "1000000";
const sc_lv<9> fc_layer3::ap_ST_fsm_state8 = "10000000";
const sc_lv<9> fc_layer3::ap_ST_fsm_state9 = "100000000";
const sc_lv<32> fc_layer3::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> fc_layer3::ap_const_lv32_8 = "1000";
const sc_lv<32> fc_layer3::ap_const_lv32_1 = "1";
const sc_lv<1> fc_layer3::ap_const_lv1_0 = "0";
const sc_lv<32> fc_layer3::ap_const_lv32_3 = "11";
const sc_lv<32> fc_layer3::ap_const_lv32_5 = "101";
const sc_lv<32> fc_layer3::ap_const_lv32_2 = "10";
const sc_lv<32> fc_layer3::ap_const_lv32_4 = "100";
const sc_lv<32> fc_layer3::ap_const_lv32_7 = "111";
const sc_lv<1> fc_layer3::ap_const_lv1_1 = "1";
const sc_lv<7> fc_layer3::ap_const_lv7_0 = "0000000";
const sc_lv<4> fc_layer3::ap_const_lv4_0 = "0000";
const sc_lv<32> fc_layer3::ap_const_lv32_6 = "110";
const sc_lv<64> fc_layer3::ap_const_lv64_0 = "0000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<16> fc_layer3::ap_const_lv16_0 = "0000000000000000";
const sc_lv<7> fc_layer3::ap_const_lv7_54 = "1010100";
const sc_lv<7> fc_layer3::ap_const_lv7_1 = "1";
const sc_lv<3> fc_layer3::ap_const_lv3_0 = "000";
const sc_lv<4> fc_layer3::ap_const_lv4_1 = "1";
const sc_lv<12> fc_layer3::ap_const_lv12_0 = "000000000000";
const sc_lv<32> fc_layer3::ap_const_lv32_C = "1100";
const sc_lv<32> fc_layer3::ap_const_lv32_1B = "11011";
const sc_lv<4> fc_layer3::ap_const_lv4_2 = "10";
const sc_lv<4> fc_layer3::ap_const_lv4_A = "1010";
const sc_lv<3> fc_layer3::ap_const_lv3_3 = "11";
const sc_lv<4> fc_layer3::ap_const_lv4_4 = "100";
const sc_lv<15> fc_layer3::ap_const_lv15_0 = "000000000000000";
const bool fc_layer3::ap_const_boolean_1 = true;

fc_layer3::fc_layer3(sc_module_name name) : sc_module(name), mVcdFile(0) {
    fc_layer3_weights_V_U = new fc_layer3_fc_layeh8b("fc_layer3_weights_V_U");
    fc_layer3_weights_V_U->clk(ap_clk);
    fc_layer3_weights_V_U->reset(ap_rst);
    fc_layer3_weights_V_U->address0(fc_layer3_weights_V_address0);
    fc_layer3_weights_V_U->ce0(fc_layer3_weights_V_ce0);
    fc_layer3_weights_V_U->q0(fc_layer3_weights_V_q0);
    fc_layer3_weights_V_U->address1(fc_layer3_weights_V_address1);
    fc_layer3_weights_V_U->ce1(fc_layer3_weights_V_ce1);
    fc_layer3_weights_V_U->q1(fc_layer3_weights_V_q1);
    output_V_U = new fc_layer3_output_V("output_V_U");
    output_V_U->clk(ap_clk);
    output_V_U->reset(ap_rst);
    output_V_U->address0(output_V_address0);
    output_V_U->ce0(output_V_ce0);
    output_V_U->we0(output_V_we0);
    output_V_U->d0(output_V_d0);
    output_V_U->q0(output_V_q0);
    output_V_U->address1(output_V_address1);
    output_V_U->ce1(output_V_ce1);
    output_V_U->we1(output_V_we1);
    output_V_U->d1(output_V_d1);
    output_V_U->q1(output_V_q1);
    nnet_mac_muladd_1h9b_U228 = new nnet_mac_muladd_1h9b<1,1,16,12,28,28>("nnet_mac_muladd_1h9b_U228");
    nnet_mac_muladd_1h9b_U228->din0(grp_fu_539_p0);
    nnet_mac_muladd_1h9b_U228->din1(reg_250);
    nnet_mac_muladd_1h9b_U228->din2(grp_fu_539_p2);
    nnet_mac_muladd_1h9b_U228->dout(grp_fu_539_p3);
    nnet_mac_muladd_1h9b_U229 = new nnet_mac_muladd_1h9b<1,1,16,12,28,28>("nnet_mac_muladd_1h9b_U229");
    nnet_mac_muladd_1h9b_U229->din0(grp_fu_547_p0);
    nnet_mac_muladd_1h9b_U229->din1(reg_254);
    nnet_mac_muladd_1h9b_U229->din2(grp_fu_547_p2);
    nnet_mac_muladd_1h9b_U229->dout(grp_fu_547_p3);
    nnet_mac_muladd_1iab_U230 = new nnet_mac_muladd_1iab<1,1,12,16,28,28>("nnet_mac_muladd_1iab_U230");
    nnet_mac_muladd_1iab_U230->din0(reg_250);
    nnet_mac_muladd_1iab_U230->din1(grp_fu_555_p1);
    nnet_mac_muladd_1iab_U230->din2(grp_fu_555_p2);
    nnet_mac_muladd_1iab_U230->dout(grp_fu_555_p3);
    nnet_mac_muladd_1iab_U231 = new nnet_mac_muladd_1iab<1,1,12,16,28,28>("nnet_mac_muladd_1iab_U231");
    nnet_mac_muladd_1iab_U231->din0(reg_254);
    nnet_mac_muladd_1iab_U231->din1(grp_fu_563_p1);
    nnet_mac_muladd_1iab_U231->din2(grp_fu_563_p2);
    nnet_mac_muladd_1iab_U231->dout(grp_fu_563_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_state1);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );

    SC_METHOD(thread_ap_block_state2);
    sensitive << ( in_V_V_empty_n );
    sensitive << ( exitcond1_fu_258_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond_fu_499_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond_fu_499_p2 );

    SC_METHOD(thread_exitcond16_2_fu_397_p2);
    sensitive << ( i_4_1_fu_391_p2 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_exitcond1_fu_258_p2);
    sensitive << ( in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_258_p2 );
    sensitive << ( j_reg_216 );

    SC_METHOD(thread_exitcond_fu_499_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( i1_reg_239 );

    SC_METHOD(thread_fc_layer3_weights_V_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_12_cast_fu_313_p1 );
    sensitive << ( tmp_14_cast_fu_412_p1 );

    SC_METHOD(thread_fc_layer3_weights_V_address1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_13_cast_fu_333_p1 );
    sensitive << ( tmp_15_cast_fu_436_p1 );

    SC_METHOD(thread_fc_layer3_weights_V_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_fc_layer3_weights_V_ce1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_grp_fu_539_p0);
    sensitive << ( tmp_2_reg_587 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_grp_fu_539_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( output_V_q0 );

    SC_METHOD(thread_grp_fu_547_p0);
    sensitive << ( tmp_2_reg_587 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_grp_fu_547_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( output_V_q1 );

    SC_METHOD(thread_grp_fu_555_p1);
    sensitive << ( tmp_2_reg_587 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_grp_fu_555_p2);
    sensitive << ( output_V_q1 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_grp_fu_563_p1);
    sensitive << ( tmp_2_reg_587 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_grp_fu_563_p2);
    sensitive << ( output_V_q0 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_i_4_1_fu_391_p2);
    sensitive << ( i3_reg_227 );

    SC_METHOD(thread_i_4_2_fu_421_p2);
    sensitive << ( tmp_17_fu_417_p1 );

    SC_METHOD(thread_i_4_3_fu_441_p2);
    sensitive << ( i3_reg_227 );

    SC_METHOD(thread_i_4_s_fu_318_p2);
    sensitive << ( i3_reg_227 );

    SC_METHOD(thread_i_fu_505_p2);
    sensitive << ( i1_reg_239 );

    SC_METHOD(thread_in_V_V_blk_n);
    sensitive << ( in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_258_p2 );

    SC_METHOD(thread_in_V_V_read);
    sensitive << ( in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_258_p2 );

    SC_METHOD(thread_j_1_fu_264_p2);
    sensitive << ( j_reg_216 );

    SC_METHOD(thread_out_V_V_blk_n);
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_out_V_V_din);
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( tmp_V_fu_526_p3 );

    SC_METHOD(thread_out_V_V_write);
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_output_V_address0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( output_V_addr_3_reg_616 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( output_V_addr_5_reg_655 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_3_fu_338_p1 );
    sensitive << ( tmp_28_3_fu_451_p1 );

    SC_METHOD(thread_output_V_address1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( output_V_addr_2_reg_610 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( output_V_addr_4_reg_650 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_28_1_fu_343_p1 );
    sensitive << ( tmp_28_2_fu_447_p1 );
    sensitive << ( tmp_s_fu_511_p1 );

    SC_METHOD(thread_output_V_ce0);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_output_V_ce1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_output_V_d0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( grp_fu_547_p3 );
    sensitive << ( grp_fu_563_p3 );

    SC_METHOD(thread_output_V_d1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( grp_fu_539_p3 );
    sensitive << ( grp_fu_555_p3 );

    SC_METHOD(thread_output_V_we0);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_output_V_we1);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_p_shl1_cast_fu_290_p1);
    sensitive << ( tmp_6_fu_282_p3 );

    SC_METHOD(thread_p_shl_cast_fu_278_p1);
    sensitive << ( tmp_fu_270_p3 );

    SC_METHOD(thread_tmp_11_fu_294_p2);
    sensitive << ( p_shl1_cast_fu_290_p1 );
    sensitive << ( p_shl_cast_fu_278_p1 );

    SC_METHOD(thread_tmp_12_cast_fu_313_p1);
    sensitive << ( tmp_12_fu_308_p2 );

    SC_METHOD(thread_tmp_12_fu_308_p2);
    sensitive << ( tmp_11_reg_579 );
    sensitive << ( tmp_3_cast_fu_304_p1 );

    SC_METHOD(thread_tmp_13_cast_fu_333_p1);
    sensitive << ( tmp_13_fu_328_p2 );

    SC_METHOD(thread_tmp_13_fu_328_p2);
    sensitive << ( tmp_11_reg_579 );
    sensitive << ( tmp_28_1_cast_fu_324_p1 );

    SC_METHOD(thread_tmp_14_cast_fu_412_p1);
    sensitive << ( tmp_14_fu_407_p2 );

    SC_METHOD(thread_tmp_14_fu_407_p2);
    sensitive << ( tmp_11_reg_579 );
    sensitive << ( tmp_28_2_cast_fu_403_p1 );

    SC_METHOD(thread_tmp_15_cast_fu_436_p1);
    sensitive << ( tmp_15_fu_431_p2 );

    SC_METHOD(thread_tmp_15_fu_431_p2);
    sensitive << ( tmp_11_reg_579 );
    sensitive << ( tmp_28_3_cast_fu_427_p1 );

    SC_METHOD(thread_tmp_16_fu_516_p1);
    sensitive << ( output_V_q1 );

    SC_METHOD(thread_tmp_17_fu_417_p1);
    sensitive << ( i3_reg_227 );

    SC_METHOD(thread_tmp_28_1_cast_fu_324_p1);
    sensitive << ( i_4_s_fu_318_p2 );

    SC_METHOD(thread_tmp_28_1_fu_343_p1);
    sensitive << ( i_4_s_reg_600 );

    SC_METHOD(thread_tmp_28_2_cast_fu_403_p1);
    sensitive << ( i_4_1_fu_391_p2 );

    SC_METHOD(thread_tmp_28_2_fu_447_p1);
    sensitive << ( i_4_1_reg_622 );

    SC_METHOD(thread_tmp_28_3_cast_fu_427_p1);
    sensitive << ( i_4_2_fu_421_p2 );

    SC_METHOD(thread_tmp_28_3_fu_451_p1);
    sensitive << ( i_4_2_reg_635 );

    SC_METHOD(thread_tmp_2_fu_300_p1);
    sensitive << ( in_V_V_dout );

    SC_METHOD(thread_tmp_3_cast_fu_304_p1);
    sensitive << ( i3_reg_227 );

    SC_METHOD(thread_tmp_3_fu_338_p1);
    sensitive << ( i3_reg_227 );

    SC_METHOD(thread_tmp_6_fu_282_p3);
    sensitive << ( j_reg_216 );

    SC_METHOD(thread_tmp_V_fu_526_p3);
    sensitive << ( tmp_i_fu_520_p2 );
    sensitive << ( tmp_16_fu_516_p1 );

    SC_METHOD(thread_tmp_fu_270_p3);
    sensitive << ( j_reg_216 );

    SC_METHOD(thread_tmp_i_fu_520_p2);
    sensitive << ( out_V_V_full_n );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( output_V_q1 );

    SC_METHOD(thread_tmp_s_fu_511_p1);
    sensitive << ( i1_reg_239 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_done_reg );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( out_V_V_full_n );
    sensitive << ( in_V_V_empty_n );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond1_fu_258_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( exitcond16_2_fu_397_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond_fu_499_p2 );

    ap_done_reg = SC_LOGIC_0;
    ap_CS_fsm = "000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "fc_layer3_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_continue, "(port)ap_continue");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, out_V_V_din, "(port)out_V_V_din");
    sc_trace(mVcdFile, out_V_V_full_n, "(port)out_V_V_full_n");
    sc_trace(mVcdFile, out_V_V_write, "(port)out_V_V_write");
    sc_trace(mVcdFile, in_V_V_dout, "(port)in_V_V_dout");
    sc_trace(mVcdFile, in_V_V_empty_n, "(port)in_V_V_empty_n");
    sc_trace(mVcdFile, in_V_V_read, "(port)in_V_V_read");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_done_reg, "ap_done_reg");
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, fc_layer3_weights_V_address0, "fc_layer3_weights_V_address0");
    sc_trace(mVcdFile, fc_layer3_weights_V_ce0, "fc_layer3_weights_V_ce0");
    sc_trace(mVcdFile, fc_layer3_weights_V_q0, "fc_layer3_weights_V_q0");
    sc_trace(mVcdFile, fc_layer3_weights_V_address1, "fc_layer3_weights_V_address1");
    sc_trace(mVcdFile, fc_layer3_weights_V_ce1, "fc_layer3_weights_V_ce1");
    sc_trace(mVcdFile, fc_layer3_weights_V_q1, "fc_layer3_weights_V_q1");
    sc_trace(mVcdFile, out_V_V_blk_n, "out_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, in_V_V_blk_n, "in_V_V_blk_n");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, exitcond1_fu_258_p2, "exitcond1_fu_258_p2");
    sc_trace(mVcdFile, reg_250, "reg_250");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, reg_254, "reg_254");
    sc_trace(mVcdFile, j_1_fu_264_p2, "j_1_fu_264_p2");
    sc_trace(mVcdFile, j_1_reg_574, "j_1_reg_574");
    sc_trace(mVcdFile, ap_block_state2, "ap_block_state2");
    sc_trace(mVcdFile, tmp_11_fu_294_p2, "tmp_11_fu_294_p2");
    sc_trace(mVcdFile, tmp_11_reg_579, "tmp_11_reg_579");
    sc_trace(mVcdFile, tmp_2_fu_300_p1, "tmp_2_fu_300_p1");
    sc_trace(mVcdFile, tmp_2_reg_587, "tmp_2_reg_587");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, i_4_s_fu_318_p2, "i_4_s_fu_318_p2");
    sc_trace(mVcdFile, i_4_s_reg_600, "i_4_s_reg_600");
    sc_trace(mVcdFile, output_V_addr_2_reg_610, "output_V_addr_2_reg_610");
    sc_trace(mVcdFile, output_V_addr_3_reg_616, "output_V_addr_3_reg_616");
    sc_trace(mVcdFile, i_4_1_fu_391_p2, "i_4_1_fu_391_p2");
    sc_trace(mVcdFile, i_4_1_reg_622, "i_4_1_reg_622");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, exitcond16_2_fu_397_p2, "exitcond16_2_fu_397_p2");
    sc_trace(mVcdFile, i_4_2_fu_421_p2, "i_4_2_fu_421_p2");
    sc_trace(mVcdFile, i_4_2_reg_635, "i_4_2_reg_635");
    sc_trace(mVcdFile, i_4_3_fu_441_p2, "i_4_3_fu_441_p2");
    sc_trace(mVcdFile, i_4_3_reg_645, "i_4_3_reg_645");
    sc_trace(mVcdFile, output_V_addr_4_reg_650, "output_V_addr_4_reg_650");
    sc_trace(mVcdFile, output_V_addr_5_reg_655, "output_V_addr_5_reg_655");
    sc_trace(mVcdFile, i_fu_505_p2, "i_fu_505_p2");
    sc_trace(mVcdFile, i_reg_663, "i_reg_663");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, exitcond_fu_499_p2, "exitcond_fu_499_p2");
    sc_trace(mVcdFile, output_V_address0, "output_V_address0");
    sc_trace(mVcdFile, output_V_ce0, "output_V_ce0");
    sc_trace(mVcdFile, output_V_we0, "output_V_we0");
    sc_trace(mVcdFile, output_V_d0, "output_V_d0");
    sc_trace(mVcdFile, output_V_q0, "output_V_q0");
    sc_trace(mVcdFile, output_V_address1, "output_V_address1");
    sc_trace(mVcdFile, output_V_ce1, "output_V_ce1");
    sc_trace(mVcdFile, output_V_we1, "output_V_we1");
    sc_trace(mVcdFile, output_V_d1, "output_V_d1");
    sc_trace(mVcdFile, output_V_q1, "output_V_q1");
    sc_trace(mVcdFile, j_reg_216, "j_reg_216");
    sc_trace(mVcdFile, ap_block_state1, "ap_block_state1");
    sc_trace(mVcdFile, i3_reg_227, "i3_reg_227");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, i1_reg_239, "i1_reg_239");
    sc_trace(mVcdFile, tmp_12_cast_fu_313_p1, "tmp_12_cast_fu_313_p1");
    sc_trace(mVcdFile, tmp_13_cast_fu_333_p1, "tmp_13_cast_fu_333_p1");
    sc_trace(mVcdFile, tmp_3_fu_338_p1, "tmp_3_fu_338_p1");
    sc_trace(mVcdFile, tmp_28_1_fu_343_p1, "tmp_28_1_fu_343_p1");
    sc_trace(mVcdFile, tmp_14_cast_fu_412_p1, "tmp_14_cast_fu_412_p1");
    sc_trace(mVcdFile, tmp_15_cast_fu_436_p1, "tmp_15_cast_fu_436_p1");
    sc_trace(mVcdFile, tmp_28_2_fu_447_p1, "tmp_28_2_fu_447_p1");
    sc_trace(mVcdFile, tmp_28_3_fu_451_p1, "tmp_28_3_fu_451_p1");
    sc_trace(mVcdFile, tmp_s_fu_511_p1, "tmp_s_fu_511_p1");
    sc_trace(mVcdFile, tmp_fu_270_p3, "tmp_fu_270_p3");
    sc_trace(mVcdFile, tmp_6_fu_282_p3, "tmp_6_fu_282_p3");
    sc_trace(mVcdFile, p_shl1_cast_fu_290_p1, "p_shl1_cast_fu_290_p1");
    sc_trace(mVcdFile, p_shl_cast_fu_278_p1, "p_shl_cast_fu_278_p1");
    sc_trace(mVcdFile, tmp_3_cast_fu_304_p1, "tmp_3_cast_fu_304_p1");
    sc_trace(mVcdFile, tmp_12_fu_308_p2, "tmp_12_fu_308_p2");
    sc_trace(mVcdFile, tmp_28_1_cast_fu_324_p1, "tmp_28_1_cast_fu_324_p1");
    sc_trace(mVcdFile, tmp_13_fu_328_p2, "tmp_13_fu_328_p2");
    sc_trace(mVcdFile, grp_fu_539_p3, "grp_fu_539_p3");
    sc_trace(mVcdFile, grp_fu_547_p3, "grp_fu_547_p3");
    sc_trace(mVcdFile, tmp_28_2_cast_fu_403_p1, "tmp_28_2_cast_fu_403_p1");
    sc_trace(mVcdFile, tmp_14_fu_407_p2, "tmp_14_fu_407_p2");
    sc_trace(mVcdFile, tmp_17_fu_417_p1, "tmp_17_fu_417_p1");
    sc_trace(mVcdFile, tmp_28_3_cast_fu_427_p1, "tmp_28_3_cast_fu_427_p1");
    sc_trace(mVcdFile, tmp_15_fu_431_p2, "tmp_15_fu_431_p2");
    sc_trace(mVcdFile, grp_fu_555_p3, "grp_fu_555_p3");
    sc_trace(mVcdFile, grp_fu_563_p3, "grp_fu_563_p3");
    sc_trace(mVcdFile, tmp_i_fu_520_p2, "tmp_i_fu_520_p2");
    sc_trace(mVcdFile, tmp_16_fu_516_p1, "tmp_16_fu_516_p1");
    sc_trace(mVcdFile, tmp_V_fu_526_p3, "tmp_V_fu_526_p3");
    sc_trace(mVcdFile, grp_fu_539_p0, "grp_fu_539_p0");
    sc_trace(mVcdFile, grp_fu_539_p2, "grp_fu_539_p2");
    sc_trace(mVcdFile, grp_fu_547_p0, "grp_fu_547_p0");
    sc_trace(mVcdFile, grp_fu_547_p2, "grp_fu_547_p2");
    sc_trace(mVcdFile, grp_fu_555_p1, "grp_fu_555_p1");
    sc_trace(mVcdFile, grp_fu_555_p2, "grp_fu_555_p2");
    sc_trace(mVcdFile, grp_fu_563_p1, "grp_fu_563_p1");
    sc_trace(mVcdFile, grp_fu_563_p2, "grp_fu_563_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

fc_layer3::~fc_layer3() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete fc_layer3_weights_V_U;
    delete output_V_U;
    delete nnet_mac_muladd_1h9b_U228;
    delete nnet_mac_muladd_1h9b_U229;
    delete nnet_mac_muladd_1iab_U230;
    delete nnet_mac_muladd_1iab_U231;
}

void fc_layer3::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_done_reg = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_continue.read())) {
            ap_done_reg = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                    esl_seteq<1,1,1>(exitcond_fu_499_p2.read(), ap_const_lv1_1))) {
            ap_done_reg = ap_const_logic_1;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         !(esl_seteq<1,1,1>(exitcond1_fu_258_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, in_V_V_empty_n.read())) && 
         esl_seteq<1,1,1>(exitcond1_fu_258_p2.read(), ap_const_lv1_1))) {
        i1_reg_239 = ap_const_lv4_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
                esl_seteq<1,1,1>(out_V_V_full_n.read(), ap_const_logic_1))) {
        i1_reg_239 = i_reg_663.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        i3_reg_227 = i_4_3_reg_645.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(exitcond1_fu_258_p2.read(), ap_const_lv1_0) && 
                !(esl_seteq<1,1,1>(exitcond1_fu_258_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, in_V_V_empty_n.read())))) {
        i3_reg_227 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
        j_reg_216 = ap_const_lv7_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(exitcond16_2_fu_397_p2.read(), ap_const_lv1_1))) {
        j_reg_216 = j_1_reg_574.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        i_4_1_reg_622 = i_4_1_fu_391_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond16_2_fu_397_p2.read()))) {
        i_4_2_reg_635 = i_4_2_fu_421_p2.read();
        i_4_3_reg_645 = i_4_3_fu_441_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        i_4_s_reg_600 = i_4_s_fu_318_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        i_reg_663 = i_fu_505_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && !(esl_seteq<1,1,1>(exitcond1_fu_258_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, in_V_V_empty_n.read())))) {
        j_1_reg_574 = j_1_fu_264_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        output_V_addr_2_reg_610 =  (sc_lv<4>) (tmp_3_fu_338_p1.read());
        output_V_addr_3_reg_616 =  (sc_lv<4>) (tmp_28_1_fu_343_p1.read());
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_V_addr_4_reg_650 =  (sc_lv<4>) (tmp_28_2_fu_447_p1.read());
        output_V_addr_5_reg_655 =  (sc_lv<4>) (tmp_28_3_fu_451_p1.read());
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        reg_250 = fc_layer3_weights_V_q0.read();
        reg_254 = fc_layer3_weights_V_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond1_fu_258_p2.read(), ap_const_lv1_0) && !(esl_seteq<1,1,1>(exitcond1_fu_258_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, in_V_V_empty_n.read())))) {
        tmp_11_reg_579 = tmp_11_fu_294_p2.read();
        tmp_2_reg_587 = tmp_2_fu_300_p1.read();
    }
}

void fc_layer3::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void fc_layer3::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void fc_layer3::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void fc_layer3::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void fc_layer3::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void fc_layer3::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void fc_layer3::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void fc_layer3::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void fc_layer3::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void fc_layer3::thread_ap_block_state1() {
    ap_block_state1 = (esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1));
}

void fc_layer3::thread_ap_block_state2() {
    ap_block_state2 = (esl_seteq<1,1,1>(exitcond1_fu_258_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, in_V_V_empty_n.read()));
}

void fc_layer3::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_499_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_done_reg.read();
    }
}

void fc_layer3::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void fc_layer3::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_499_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void fc_layer3::thread_exitcond16_2_fu_397_p2() {
    exitcond16_2_fu_397_p2 = (!i_4_1_fu_391_p2.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(i_4_1_fu_391_p2.read() == ap_const_lv4_A);
}

void fc_layer3::thread_exitcond1_fu_258_p2() {
    exitcond1_fu_258_p2 = (!j_reg_216.read().is_01() || !ap_const_lv7_54.is_01())? sc_lv<1>(): sc_lv<1>(j_reg_216.read() == ap_const_lv7_54);
}

void fc_layer3::thread_exitcond_fu_499_p2() {
    exitcond_fu_499_p2 = (!i1_reg_239.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(i1_reg_239.read() == ap_const_lv4_A);
}

void fc_layer3::thread_fc_layer3_weights_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        fc_layer3_weights_V_address0 =  (sc_lv<10>) (tmp_14_cast_fu_412_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        fc_layer3_weights_V_address0 =  (sc_lv<10>) (tmp_12_cast_fu_313_p1.read());
    } else {
        fc_layer3_weights_V_address0 = "XXXXXXXXXX";
    }
}

void fc_layer3::thread_fc_layer3_weights_V_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        fc_layer3_weights_V_address1 =  (sc_lv<10>) (tmp_15_cast_fu_436_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        fc_layer3_weights_V_address1 =  (sc_lv<10>) (tmp_13_cast_fu_333_p1.read());
    } else {
        fc_layer3_weights_V_address1 = "XXXXXXXXXX";
    }
}

void fc_layer3::thread_fc_layer3_weights_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        fc_layer3_weights_V_ce0 = ap_const_logic_1;
    } else {
        fc_layer3_weights_V_ce0 = ap_const_logic_0;
    }
}

void fc_layer3::thread_fc_layer3_weights_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()))) {
        fc_layer3_weights_V_ce1 = ap_const_logic_1;
    } else {
        fc_layer3_weights_V_ce1 = ap_const_logic_0;
    }
}

void fc_layer3::thread_grp_fu_539_p0() {
    grp_fu_539_p0 =  (sc_lv<16>) (tmp_2_reg_587.read());
}

void fc_layer3::thread_grp_fu_539_p2() {
    grp_fu_539_p2 = esl_concat<16,12>(output_V_q0.read(), ap_const_lv12_0);
}

void fc_layer3::thread_grp_fu_547_p0() {
    grp_fu_547_p0 =  (sc_lv<16>) (tmp_2_reg_587.read());
}

void fc_layer3::thread_grp_fu_547_p2() {
    grp_fu_547_p2 = esl_concat<16,12>(output_V_q1.read(), ap_const_lv12_0);
}

void fc_layer3::thread_grp_fu_555_p1() {
    grp_fu_555_p1 =  (sc_lv<16>) (tmp_2_reg_587.read());
}

void fc_layer3::thread_grp_fu_555_p2() {
    grp_fu_555_p2 = esl_concat<16,12>(output_V_q1.read(), ap_const_lv12_0);
}

void fc_layer3::thread_grp_fu_563_p1() {
    grp_fu_563_p1 =  (sc_lv<16>) (tmp_2_reg_587.read());
}

void fc_layer3::thread_grp_fu_563_p2() {
    grp_fu_563_p2 = esl_concat<16,12>(output_V_q0.read(), ap_const_lv12_0);
}

void fc_layer3::thread_i_4_1_fu_391_p2() {
    i_4_1_fu_391_p2 = (i3_reg_227.read() | ap_const_lv4_2);
}

void fc_layer3::thread_i_4_2_fu_421_p2() {
    i_4_2_fu_421_p2 = (tmp_17_fu_417_p1.read() | ap_const_lv3_3);
}

void fc_layer3::thread_i_4_3_fu_441_p2() {
    i_4_3_fu_441_p2 = (!ap_const_lv4_4.is_01() || !i3_reg_227.read().is_01())? sc_lv<4>(): (sc_biguint<4>(ap_const_lv4_4) + sc_biguint<4>(i3_reg_227.read()));
}

void fc_layer3::thread_i_4_s_fu_318_p2() {
    i_4_s_fu_318_p2 = (i3_reg_227.read() | ap_const_lv4_1);
}

void fc_layer3::thread_i_fu_505_p2() {
    i_fu_505_p2 = (!i1_reg_239.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i1_reg_239.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void fc_layer3::thread_in_V_V_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_258_p2.read(), ap_const_lv1_0))) {
        in_V_V_blk_n = in_V_V_empty_n.read();
    } else {
        in_V_V_blk_n = ap_const_logic_1;
    }
}

void fc_layer3::thread_in_V_V_read() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_258_p2.read(), ap_const_lv1_0) && 
         !(esl_seteq<1,1,1>(exitcond1_fu_258_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, in_V_V_empty_n.read())))) {
        in_V_V_read = ap_const_logic_1;
    } else {
        in_V_V_read = ap_const_logic_0;
    }
}

void fc_layer3::thread_j_1_fu_264_p2() {
    j_1_fu_264_p2 = (!j_reg_216.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(j_reg_216.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void fc_layer3::thread_out_V_V_blk_n() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        out_V_V_blk_n = out_V_V_full_n.read();
    } else {
        out_V_V_blk_n = ap_const_logic_1;
    }
}

void fc_layer3::thread_out_V_V_din() {
    out_V_V_din = esl_zext<16,15>(tmp_V_fu_526_p3.read());
}

void fc_layer3::thread_out_V_V_write() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(out_V_V_full_n.read(), ap_const_logic_1))) {
        out_V_V_write = ap_const_logic_1;
    } else {
        out_V_V_write = ap_const_logic_0;
    }
}

void fc_layer3::thread_output_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_V_address0 = output_V_addr_5_reg_655.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_V_address0 =  (sc_lv<4>) (tmp_28_3_fu_451_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        output_V_address0 = output_V_addr_3_reg_616.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        output_V_address0 =  (sc_lv<4>) (tmp_3_fu_338_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        output_V_address0 =  (sc_lv<4>) (ap_const_lv64_0);
    } else {
        output_V_address0 =  (sc_lv<4>) ("XXXX");
    }
}

void fc_layer3::thread_output_V_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        output_V_address1 =  (sc_lv<4>) (tmp_s_fu_511_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_V_address1 = output_V_addr_4_reg_650.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_V_address1 =  (sc_lv<4>) (tmp_28_2_fu_447_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        output_V_address1 = output_V_addr_2_reg_610.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        output_V_address1 =  (sc_lv<4>) (tmp_28_1_fu_343_p1.read());
    } else {
        output_V_address1 =  (sc_lv<4>) ("XXXX");
    }
}

void fc_layer3::thread_output_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        output_V_ce0 = ap_const_logic_1;
    } else {
        output_V_ce0 = ap_const_logic_0;
    }
}

void fc_layer3::thread_output_V_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        output_V_ce1 = ap_const_logic_1;
    } else {
        output_V_ce1 = ap_const_logic_0;
    }
}

void fc_layer3::thread_output_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_V_d0 = grp_fu_563_p3.read().range(27, 12);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        output_V_d0 = grp_fu_547_p3.read().range(27, 12);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) {
        output_V_d0 = ap_const_lv16_0;
    } else {
        output_V_d0 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void fc_layer3::thread_output_V_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_V_d1 = grp_fu_555_p3.read().range(27, 12);
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        output_V_d1 = grp_fu_539_p3.read().range(27, 12);
    } else {
        output_V_d1 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void fc_layer3::thread_output_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1))) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        output_V_we0 = ap_const_logic_1;
    } else {
        output_V_we0 = ap_const_logic_0;
    }
}

void fc_layer3::thread_output_V_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        output_V_we1 = ap_const_logic_1;
    } else {
        output_V_we1 = ap_const_logic_0;
    }
}

void fc_layer3::thread_p_shl1_cast_fu_290_p1() {
    p_shl1_cast_fu_290_p1 = esl_zext<11,8>(tmp_6_fu_282_p3.read());
}

void fc_layer3::thread_p_shl_cast_fu_278_p1() {
    p_shl_cast_fu_278_p1 = esl_zext<11,10>(tmp_fu_270_p3.read());
}

void fc_layer3::thread_tmp_11_fu_294_p2() {
    tmp_11_fu_294_p2 = (!p_shl1_cast_fu_290_p1.read().is_01() || !p_shl_cast_fu_278_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(p_shl1_cast_fu_290_p1.read()) + sc_biguint<11>(p_shl_cast_fu_278_p1.read()));
}

void fc_layer3::thread_tmp_12_cast_fu_313_p1() {
    tmp_12_cast_fu_313_p1 = esl_zext<64,11>(tmp_12_fu_308_p2.read());
}

void fc_layer3::thread_tmp_12_fu_308_p2() {
    tmp_12_fu_308_p2 = (!tmp_3_cast_fu_304_p1.read().is_01() || !tmp_11_reg_579.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_3_cast_fu_304_p1.read()) + sc_biguint<11>(tmp_11_reg_579.read()));
}

void fc_layer3::thread_tmp_13_cast_fu_333_p1() {
    tmp_13_cast_fu_333_p1 = esl_zext<64,11>(tmp_13_fu_328_p2.read());
}

void fc_layer3::thread_tmp_13_fu_328_p2() {
    tmp_13_fu_328_p2 = (!tmp_28_1_cast_fu_324_p1.read().is_01() || !tmp_11_reg_579.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_28_1_cast_fu_324_p1.read()) + sc_biguint<11>(tmp_11_reg_579.read()));
}

void fc_layer3::thread_tmp_14_cast_fu_412_p1() {
    tmp_14_cast_fu_412_p1 = esl_zext<64,11>(tmp_14_fu_407_p2.read());
}

void fc_layer3::thread_tmp_14_fu_407_p2() {
    tmp_14_fu_407_p2 = (!tmp_11_reg_579.read().is_01() || !tmp_28_2_cast_fu_403_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_11_reg_579.read()) + sc_biguint<11>(tmp_28_2_cast_fu_403_p1.read()));
}

void fc_layer3::thread_tmp_15_cast_fu_436_p1() {
    tmp_15_cast_fu_436_p1 = esl_zext<64,11>(tmp_15_fu_431_p2.read());
}

void fc_layer3::thread_tmp_15_fu_431_p2() {
    tmp_15_fu_431_p2 = (!tmp_11_reg_579.read().is_01() || !tmp_28_3_cast_fu_427_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_11_reg_579.read()) + sc_biguint<11>(tmp_28_3_cast_fu_427_p1.read()));
}

void fc_layer3::thread_tmp_16_fu_516_p1() {
    tmp_16_fu_516_p1 = output_V_q1.read().range(15-1, 0);
}

void fc_layer3::thread_tmp_17_fu_417_p1() {
    tmp_17_fu_417_p1 = i3_reg_227.read().range(3-1, 0);
}

void fc_layer3::thread_tmp_28_1_cast_fu_324_p1() {
    tmp_28_1_cast_fu_324_p1 = esl_zext<11,4>(i_4_s_fu_318_p2.read());
}

void fc_layer3::thread_tmp_28_1_fu_343_p1() {
    tmp_28_1_fu_343_p1 = esl_zext<64,4>(i_4_s_reg_600.read());
}

void fc_layer3::thread_tmp_28_2_cast_fu_403_p1() {
    tmp_28_2_cast_fu_403_p1 = esl_zext<11,4>(i_4_1_fu_391_p2.read());
}

void fc_layer3::thread_tmp_28_2_fu_447_p1() {
    tmp_28_2_fu_447_p1 = esl_zext<64,4>(i_4_1_reg_622.read());
}

void fc_layer3::thread_tmp_28_3_cast_fu_427_p1() {
    tmp_28_3_cast_fu_427_p1 = esl_zext<11,3>(i_4_2_fu_421_p2.read());
}

void fc_layer3::thread_tmp_28_3_fu_451_p1() {
    tmp_28_3_fu_451_p1 = esl_zext<64,3>(i_4_2_reg_635.read());
}

void fc_layer3::thread_tmp_2_fu_300_p1() {
    tmp_2_fu_300_p1 = esl_sext<28,16>(in_V_V_dout.read());
}

void fc_layer3::thread_tmp_3_cast_fu_304_p1() {
    tmp_3_cast_fu_304_p1 = esl_zext<11,4>(i3_reg_227.read());
}

void fc_layer3::thread_tmp_3_fu_338_p1() {
    tmp_3_fu_338_p1 = esl_zext<64,4>(i3_reg_227.read());
}

void fc_layer3::thread_tmp_6_fu_282_p3() {
    tmp_6_fu_282_p3 = esl_concat<7,1>(j_reg_216.read(), ap_const_lv1_0);
}

void fc_layer3::thread_tmp_V_fu_526_p3() {
    tmp_V_fu_526_p3 = (!tmp_i_fu_520_p2.read()[0].is_01())? sc_lv<15>(): ((tmp_i_fu_520_p2.read()[0].to_bool())? tmp_16_fu_516_p1.read(): ap_const_lv15_0);
}

void fc_layer3::thread_tmp_fu_270_p3() {
    tmp_fu_270_p3 = esl_concat<7,3>(j_reg_216.read(), ap_const_lv3_0);
}

void fc_layer3::thread_tmp_i_fu_520_p2() {
    tmp_i_fu_520_p2 = (!output_V_q1.read().is_01() || !ap_const_lv16_0.is_01())? sc_lv<1>(): (sc_bigint<16>(output_V_q1.read()) > sc_bigint<16>(ap_const_lv16_0));
}

void fc_layer3::thread_tmp_s_fu_511_p1() {
    tmp_s_fu_511_p1 = esl_zext<64,4>(i1_reg_239.read());
}

void fc_layer3::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_done_reg.read(), ap_const_logic_1)))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && !(esl_seteq<1,1,1>(exitcond1_fu_258_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, in_V_V_empty_n.read())) && esl_seteq<1,1,1>(exitcond1_fu_258_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond1_fu_258_p2.read(), ap_const_lv1_0) && !(esl_seteq<1,1,1>(exitcond1_fu_258_p2.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_0, in_V_V_empty_n.read())))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(exitcond16_2_fu_397_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(exitcond_fu_499_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(out_V_V_full_n.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        default : 
            ap_NS_fsm =  (sc_lv<9>) ("XXXXXXXXX");
            break;
    }
}

}

