// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __fc_layer3_fc_layeigb_H__
#define __fc_layer3_fc_layeigb_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct fc_layer3_fc_layeigb_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 12;
  static const unsigned AddressRange = 84;
  static const unsigned AddressWidth = 7;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(fc_layer3_fc_layeigb_ram) {
        ram[0] = "0b001101101101";
        ram[1] = "0b001010110111";
        ram[2] = "0b111110000101";
        ram[3] = "0b001110101000";
        ram[4] = "0b111101000000";
        ram[5] = "0b001101110101";
        ram[6] = "0b000010001000";
        ram[7] = "0b000001111100";
        ram[8] = "0b000101100101";
        ram[9] = "0b001010010101";
        ram[10] = "0b001101001010";
        ram[11] = "0b111011001110";
        ram[12] = "0b001111011001";
        ram[13] = "0b110110001000";
        ram[14] = "0b001100100000";
        ram[15] = "0b000101001101";
        ram[16] = "0b111110011110";
        ram[17] = "0b000110110100";
        ram[18] = "0b111001011100";
        ram[19] = "0b001100010101";
        ram[20] = "0b000101110010";
        ram[21] = "0b110010111111";
        ram[22] = "0b111111111010";
        ram[23] = "0b111101101100";
        ram[24] = "0b111011010010";
        ram[25] = "0b110011010010";
        ram[26] = "0b000010111001";
        ram[27] = "0b000110110111";
        ram[28] = "0b110001111101";
        ram[29] = "0b111010101100";
        ram[30] = "0b111100001101";
        ram[31] = "0b001111110100";
        ram[32] = "0b110110010110";
        ram[33] = "0b110011101010";
        ram[34] = "0b110001000010";
        ram[35] = "0b000111000000";
        ram[36] = "0b111000110010";
        ram[37] = "0b000110010001";
        ram[38] = "0b110100101101";
        ram[39] = "0b000000101101";
        ram[40] = "0b110011111101";
        ram[41] = "0b110000111110";
        ram[42] = "0b110110110101";
        ram[43] = "0b001100110101";
        ram[44] = "0b111100110100";
        ram[45] = "0b000011100110";
        ram[46] = "0b001111101011";
        ram[47] = "0b001110100011";
        ram[48] = "0b110111000001";
        ram[49] = "0b111100011110";
        ram[50] = "0b110111110101";
        ram[51] = "0b111111101111";
        ram[52] = "0b000101100000";
        ram[53] = "0b000101011101";
        ram[54] = "0b001011001001";
        ram[55] = "0b000110111101";
        ram[56] = "0b111101101000";
        ram[57] = "0b110001010100";
        ram[58] = "0b110000100100";
        ram[59] = "0b001110011010";
        ram[60] = "0b000001100101";
        ram[61] = "0b110110010110";
        ram[62] = "0b111011111011";
        ram[63] = "0b110000000110";
        ram[64] = "0b110110000000";
        ram[65] = "0b111010001111";
        ram[66] = "0b111101001000";
        ram[67] = "0b111010101001";
        ram[68] = "0b001011001010";
        ram[69] = "0b101111110110";
        ram[70] = "0b111001111110";
        ram[71] = "0b110101101100";
        ram[72] = "0b111001011111";
        ram[73] = "0b000101010101";
        ram[74] = "0b110100100000";
        ram[75] = "0b111101110111";
        ram[76] = "0b110010101000";
        ram[77] = "0b000000100101";
        ram[78] = "0b000001110011";
        ram[79] = "0b110111110101";
        ram[80] = "0b110001110011";
        ram[81] = "0b000101010100";
        ram[82] = "0b111100111101";
        ram[83] = "0b110100000001";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(fc_layer3_fc_layeigb) {


static const unsigned DataWidth = 12;
static const unsigned AddressRange = 84;
static const unsigned AddressWidth = 7;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


fc_layer3_fc_layeigb_ram* meminst;


SC_CTOR(fc_layer3_fc_layeigb) {
meminst = new fc_layer3_fc_layeigb_ram("fc_layer3_fc_layeigb_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~fc_layer3_fc_layeigb() {
    delete meminst;
}


};//endmodule
#endif
