// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __conv_layer2_conv_PgM_H__
#define __conv_layer2_conv_PgM_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct conv_layer2_conv_PgM_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 19;
  static const unsigned AddressRange = 16;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(conv_layer2_conv_PgM_ram) {
        ram[0] = "0b1101110111101100111";
        ram[1] = "0b0101111001001110100";
        ram[2] = "0b0011010101011110110";
        ram[3] = "0b1010001001000011010";
        ram[4] = "0b1001111001001111001";
        ram[5] = "0b1000000101011110001";
        ram[6] = "0b1001000011000001100";
        ram[7] = "0b1010110111100100111";
        ram[8] = "0b1111110010000111111";
        ram[9] = "0b1011000010101101001";
        ram[10] = "0b0000100000110011100";
        ram[11] = "0b1100111111101010010";
        ram[12] = "0b0111100001010000010";
        ram[13] = "0b1100110011100010000";
        ram[14] = "0b0111100111100111011";
        ram[15] = "0b1101000000001001111";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(conv_layer2_conv_PgM) {


static const unsigned DataWidth = 19;
static const unsigned AddressRange = 16;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


conv_layer2_conv_PgM_ram* meminst;


SC_CTOR(conv_layer2_conv_PgM) {
meminst = new conv_layer2_conv_PgM_ram("conv_layer2_conv_PgM_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~conv_layer2_conv_PgM() {
    delete meminst;
}


};//endmodule
#endif
