// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __conv_layer2_conv_zec_H__
#define __conv_layer2_conv_zec_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct conv_layer2_conv_zec_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 19;
  static const unsigned AddressRange = 16;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(conv_layer2_conv_zec_ram) {
        ram[0] = "0b1010011101111110010";
        ram[1] = "0b1111010110000110011";
        ram[2] = "0b0100001000011101111";
        ram[3] = "0b1100000101001100101";
        ram[4] = "0b0101000110001110110";
        ram[5] = "0b1100100000000010001";
        ram[6] = "0b0110100010100010001";
        ram[7] = "0b0010111000001001100";
        ram[8] = "0b0001010110011111100";
        ram[9] = "0b0101000110011000011";
        ram[10] = "0b0100101010100010010";
        ram[11] = "0b1111001111010011111";
        ram[12] = "0b1010100001001001011";
        ram[13] = "0b1100001101010101010";
        ram[14] = "0b0011010100111011001";
        ram[15] = "0b1100011000000100110";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(conv_layer2_conv_zec) {


static const unsigned DataWidth = 19;
static const unsigned AddressRange = 16;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


conv_layer2_conv_zec_ram* meminst;


SC_CTOR(conv_layer2_conv_zec) {
meminst = new conv_layer2_conv_zec_ram("conv_layer2_conv_zec_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~conv_layer2_conv_zec() {
    delete meminst;
}


};//endmodule
#endif
