// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "nnet.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic nnet::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic nnet::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<26> nnet::ap_ST_fsm_state1 = "1";
const sc_lv<26> nnet::ap_ST_fsm_state2 = "10";
const sc_lv<26> nnet::ap_ST_fsm_state3 = "100";
const sc_lv<26> nnet::ap_ST_fsm_state4 = "1000";
const sc_lv<26> nnet::ap_ST_fsm_state5 = "10000";
const sc_lv<26> nnet::ap_ST_fsm_state6 = "100000";
const sc_lv<26> nnet::ap_ST_fsm_state7 = "1000000";
const sc_lv<26> nnet::ap_ST_fsm_state8 = "10000000";
const sc_lv<26> nnet::ap_ST_fsm_state9 = "100000000";
const sc_lv<26> nnet::ap_ST_fsm_state10 = "1000000000";
const sc_lv<26> nnet::ap_ST_fsm_state11 = "10000000000";
const sc_lv<26> nnet::ap_ST_fsm_state12 = "100000000000";
const sc_lv<26> nnet::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<26> nnet::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<26> nnet::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<26> nnet::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<26> nnet::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<26> nnet::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<26> nnet::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<26> nnet::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<26> nnet::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<26> nnet::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<26> nnet::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<26> nnet::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<26> nnet::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<26> nnet::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<32> nnet::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> nnet::ap_const_lv32_8 = "1000";
const sc_lv<1> nnet::ap_const_lv1_0 = "0";
const sc_lv<32> nnet::ap_const_lv32_9 = "1001";
const sc_lv<32> nnet::ap_const_lv32_A = "1010";
const sc_lv<32> nnet::ap_const_lv32_B = "1011";
const sc_lv<32> nnet::ap_const_lv32_C = "1100";
const sc_lv<32> nnet::ap_const_lv32_E = "1110";
const sc_lv<32> nnet::ap_const_lv32_F = "1111";
const sc_lv<32> nnet::ap_const_lv32_10 = "10000";
const sc_lv<32> nnet::ap_const_lv32_11 = "10001";
const sc_lv<32> nnet::ap_const_lv32_12 = "10010";
const sc_lv<32> nnet::ap_const_lv32_14 = "10100";
const sc_lv<32> nnet::ap_const_lv32_15 = "10101";
const sc_lv<32> nnet::ap_const_lv32_16 = "10110";
const sc_lv<32> nnet::ap_const_lv32_17 = "10111";
const sc_lv<32> nnet::ap_const_lv32_18 = "11000";
const sc_lv<7> nnet::ap_const_lv7_0 = "0000000";
const sc_lv<32> nnet::ap_const_lv32_7 = "111";
const sc_lv<32> nnet::ap_const_lv32_D = "1101";
const sc_lv<24> nnet::ap_const_lv24_0 = "000000000000000000000000";
const sc_lv<10> nnet::ap_const_lv10_0 = "0000000000";
const sc_lv<32> nnet::ap_const_lv32_13 = "10011";
const sc_lv<1> nnet::ap_const_lv1_1 = "1";
const sc_lv<14> nnet::ap_const_lv14_0 = "00000000000000";
const sc_lv<32> nnet::ap_const_lv32_19 = "11001";
const sc_lv<4> nnet::ap_const_lv4_0 = "0000";
const sc_lv<32> nnet::ap_const_lv32_6 = "110";
const sc_lv<32> nnet::ap_const_lv32_4 = "100";
const sc_lv<32> nnet::ap_const_lv32_5 = "101";
const sc_lv<32> nnet::ap_const_lv32_2 = "10";
const sc_lv<32> nnet::ap_const_lv32_3 = "11";
const sc_lv<32> nnet::ap_const_lv32_1 = "1";
const sc_lv<7> nnet::ap_const_lv7_78 = "1111000";
const sc_lv<7> nnet::ap_const_lv7_1 = "1";
const sc_lv<10> nnet::ap_const_lv10_240 = "1001000000";
const sc_lv<10> nnet::ap_const_lv10_1 = "1";
const sc_lv<3> nnet::ap_const_lv3_0 = "000";
const sc_lv<20> nnet::ap_const_lv20_0 = "00000000000000000000";
const sc_lv<32> nnet::ap_const_lv32_2B = "101011";
const sc_lv<23> nnet::ap_const_lv23_0 = "00000000000000000000000";
const sc_lv<7> nnet::ap_const_lv7_54 = "1010100";
const sc_lv<14> nnet::ap_const_lv14_54 = "1010100";
const sc_lv<4> nnet::ap_const_lv4_A = "1010";
const sc_lv<4> nnet::ap_const_lv4_1 = "1";
const bool nnet::ap_const_boolean_1 = true;

nnet::nnet(sc_module_name name) : sc_module(name), mVcdFile(0) {
    fc_layer1_weights_V_U = new nnet_fc_layer1_we1iI("fc_layer1_weights_V_U");
    fc_layer1_weights_V_U->clk(ap_clk);
    fc_layer1_weights_V_U->reset(ap_rst);
    fc_layer1_weights_V_U->address0(fc_layer1_weights_V_address0);
    fc_layer1_weights_V_U->ce0(fc_layer1_weights_V_ce0);
    fc_layer1_weights_V_U->q0(fc_layer1_weights_V_q0);
    fc_layer2_weights_V_U = new nnet_fc_layer2_we2iS("fc_layer2_weights_V_U");
    fc_layer2_weights_V_U->clk(ap_clk);
    fc_layer2_weights_V_U->reset(ap_rst);
    fc_layer2_weights_V_U->address0(fc_layer2_weights_V_address0);
    fc_layer2_weights_V_U->ce0(fc_layer2_weights_V_ce0);
    fc_layer2_weights_V_U->q0(fc_layer2_weights_V_q0);
    fc_layer3_weights_V_U = new nnet_fc_layer3_we3i2("fc_layer3_weights_V_U");
    fc_layer3_weights_V_U->clk(ap_clk);
    fc_layer3_weights_V_U->reset(ap_rst);
    fc_layer3_weights_V_U->address0(fc_layer3_weights_V_address0);
    fc_layer3_weights_V_U->ce0(fc_layer3_weights_V_ce0);
    fc_layer3_weights_V_U->q0(fc_layer3_weights_V_q0);
    grp_pool_layer2_fu_429 = new pool_layer2("grp_pool_layer2_fu_429");
    grp_pool_layer2_fu_429->ap_clk(ap_clk);
    grp_pool_layer2_fu_429->ap_rst(ap_rst);
    grp_pool_layer2_fu_429->ap_start(grp_pool_layer2_fu_429_ap_start);
    grp_pool_layer2_fu_429->ap_done(grp_pool_layer2_fu_429_ap_done);
    grp_pool_layer2_fu_429->ap_idle(grp_pool_layer2_fu_429_ap_idle);
    grp_pool_layer2_fu_429->ap_ready(grp_pool_layer2_fu_429_ap_ready);
    grp_pool_layer2_fu_429->output_V_address0(grp_pool_layer2_fu_429_output_V_address0);
    grp_pool_layer2_fu_429->output_V_ce0(grp_pool_layer2_fu_429_output_V_ce0);
    grp_pool_layer2_fu_429->output_V_we0(grp_pool_layer2_fu_429_output_V_we0);
    grp_pool_layer2_fu_429->output_V_d0(grp_pool_layer2_fu_429_output_V_d0);
    grp_pool_layer2_fu_429->output_V_address1(grp_pool_layer2_fu_429_output_V_address1);
    grp_pool_layer2_fu_429->output_V_ce1(grp_pool_layer2_fu_429_output_V_ce1);
    grp_pool_layer2_fu_429->output_V_we1(grp_pool_layer2_fu_429_output_V_we1);
    grp_pool_layer2_fu_429->output_V_d1(grp_pool_layer2_fu_429_output_V_d1);
    grp_pool_layer2_fu_429->image_V_address0(grp_pool_layer2_fu_429_image_V_address0);
    grp_pool_layer2_fu_429->image_V_ce0(grp_pool_layer2_fu_429_image_V_ce0);
    grp_pool_layer2_fu_429->image_V_q0(conv_layer2_out_V_q0);
    grp_pool_layer2_fu_429->image_V_address1(grp_pool_layer2_fu_429_image_V_address1);
    grp_pool_layer2_fu_429->image_V_ce1(grp_pool_layer2_fu_429_image_V_ce1);
    grp_pool_layer2_fu_429->image_V_q1(conv_layer2_out_V_q1);
    grp_conv_layer2_fu_437 = new conv_layer2("grp_conv_layer2_fu_437");
    grp_conv_layer2_fu_437->ap_clk(ap_clk);
    grp_conv_layer2_fu_437->ap_rst(ap_rst);
    grp_conv_layer2_fu_437->ap_start(grp_conv_layer2_fu_437_ap_start);
    grp_conv_layer2_fu_437->ap_done(grp_conv_layer2_fu_437_ap_done);
    grp_conv_layer2_fu_437->ap_idle(grp_conv_layer2_fu_437_ap_idle);
    grp_conv_layer2_fu_437->ap_ready(grp_conv_layer2_fu_437_ap_ready);
    grp_conv_layer2_fu_437->output_V_address0(grp_conv_layer2_fu_437_output_V_address0);
    grp_conv_layer2_fu_437->output_V_ce0(grp_conv_layer2_fu_437_output_V_ce0);
    grp_conv_layer2_fu_437->output_V_we0(grp_conv_layer2_fu_437_output_V_we0);
    grp_conv_layer2_fu_437->output_V_d0(grp_conv_layer2_fu_437_output_V_d0);
    grp_conv_layer2_fu_437->image_V_address0(grp_conv_layer2_fu_437_image_V_address0);
    grp_conv_layer2_fu_437->image_V_ce0(grp_conv_layer2_fu_437_image_V_ce0);
    grp_conv_layer2_fu_437->image_V_q0(pool_layer1_out_V_q0);
    grp_conv_layer2_fu_437->image_V_address1(grp_conv_layer2_fu_437_image_V_address1);
    grp_conv_layer2_fu_437->image_V_ce1(grp_conv_layer2_fu_437_image_V_ce1);
    grp_conv_layer2_fu_437->image_V_q1(pool_layer1_out_V_q1);
    grp_pool_layer1_fu_511 = new pool_layer1("grp_pool_layer1_fu_511");
    grp_pool_layer1_fu_511->ap_clk(ap_clk);
    grp_pool_layer1_fu_511->ap_rst(ap_rst);
    grp_pool_layer1_fu_511->ap_start(grp_pool_layer1_fu_511_ap_start);
    grp_pool_layer1_fu_511->ap_done(grp_pool_layer1_fu_511_ap_done);
    grp_pool_layer1_fu_511->ap_idle(grp_pool_layer1_fu_511_ap_idle);
    grp_pool_layer1_fu_511->ap_ready(grp_pool_layer1_fu_511_ap_ready);
    grp_pool_layer1_fu_511->output_V_address0(grp_pool_layer1_fu_511_output_V_address0);
    grp_pool_layer1_fu_511->output_V_ce0(grp_pool_layer1_fu_511_output_V_ce0);
    grp_pool_layer1_fu_511->output_V_we0(grp_pool_layer1_fu_511_output_V_we0);
    grp_pool_layer1_fu_511->output_V_d0(grp_pool_layer1_fu_511_output_V_d0);
    grp_pool_layer1_fu_511->output_V_address1(grp_pool_layer1_fu_511_output_V_address1);
    grp_pool_layer1_fu_511->output_V_ce1(grp_pool_layer1_fu_511_output_V_ce1);
    grp_pool_layer1_fu_511->output_V_we1(grp_pool_layer1_fu_511_output_V_we1);
    grp_pool_layer1_fu_511->output_V_d1(grp_pool_layer1_fu_511_output_V_d1);
    grp_pool_layer1_fu_511->image_V_address0(grp_pool_layer1_fu_511_image_V_address0);
    grp_pool_layer1_fu_511->image_V_ce0(grp_pool_layer1_fu_511_image_V_ce0);
    grp_pool_layer1_fu_511->image_V_q0(conv_layer1_out_V_q0);
    grp_pool_layer1_fu_511->image_V_address1(grp_pool_layer1_fu_511_image_V_address1);
    grp_pool_layer1_fu_511->image_V_ce1(grp_pool_layer1_fu_511_image_V_ce1);
    grp_pool_layer1_fu_511->image_V_q1(conv_layer1_out_V_q1);
    grp_conv_layer1_fu_519 = new conv_layer1("grp_conv_layer1_fu_519");
    grp_conv_layer1_fu_519->ap_clk(ap_clk);
    grp_conv_layer1_fu_519->ap_rst(ap_rst);
    grp_conv_layer1_fu_519->ap_start(grp_conv_layer1_fu_519_ap_start);
    grp_conv_layer1_fu_519->ap_done(grp_conv_layer1_fu_519_ap_done);
    grp_conv_layer1_fu_519->ap_idle(grp_conv_layer1_fu_519_ap_idle);
    grp_conv_layer1_fu_519->ap_ready(grp_conv_layer1_fu_519_ap_ready);
    grp_conv_layer1_fu_519->output_V_address0(grp_conv_layer1_fu_519_output_V_address0);
    grp_conv_layer1_fu_519->output_V_ce0(grp_conv_layer1_fu_519_output_V_ce0);
    grp_conv_layer1_fu_519->output_V_we0(grp_conv_layer1_fu_519_output_V_we0);
    grp_conv_layer1_fu_519->output_V_d0(grp_conv_layer1_fu_519_output_V_d0);
    nnet_mul_mul_24s_4jc_U109 = new nnet_mul_mul_24s_4jc<1,1,24,18,41>("nnet_mul_mul_24s_4jc_U109");
    nnet_mul_mul_24s_4jc_U109->din0(pool_layer2_out_V_lo_reg_998);
    nnet_mul_mul_24s_4jc_U109->din1(fc_layer1_weights_V_1_reg_993);
    nnet_mul_mul_24s_4jc_U109->dout(p_Val2_1_fu_945_p2);
    nnet_mul_mul_24s_5jm_U110 = new nnet_mul_mul_24s_5jm<1,1,24,19,42>("nnet_mul_mul_24s_5jm_U110");
    nnet_mul_mul_24s_5jm_U110->din0(fc_layer1_out_V_load_reg_1059);
    nnet_mul_mul_24s_5jm_U110->din1(fc_layer2_weights_V_1_reg_1054);
    nnet_mul_mul_24s_5jm_U110->dout(p_Val2_4_fu_951_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_V_i_i1_cast_fu_800_p1);
    sensitive << ( a_V_i_i1_fu_792_p3 );

    SC_METHOD(thread_a_V_i_i1_fu_792_p3);
    sensitive << ( tmp_i_i1_fu_786_p2 );
    sensitive << ( tmp_10_fu_782_p1 );

    SC_METHOD(thread_a_V_i_i2_cast_fu_940_p1);
    sensitive << ( a_V_i_i2_fu_932_p3 );

    SC_METHOD(thread_a_V_i_i2_fu_932_p3);
    sensitive << ( tmp_i_i2_fu_926_p2 );
    sensitive << ( tmp_11_fu_922_p1 );

    SC_METHOD(thread_a_V_i_i_cast_fu_690_p1);
    sensitive << ( a_V_i_i_fu_682_p3 );

    SC_METHOD(thread_a_V_i_i_fu_682_p3);
    sensitive << ( tmp_i_i_fu_676_p2 );
    sensitive << ( tmp_4_fu_672_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state20);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state21);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state22);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state25);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state26);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( exitcond5_i_fu_805_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( exitcond5_i_fu_805_p2 );

    SC_METHOD(thread_conv_layer1_out_V_address0);
    sensitive << ( grp_pool_layer1_fu_511_image_V_address0 );
    sensitive << ( grp_conv_layer1_fu_519_output_V_address0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_conv_layer1_out_V_address1);
    sensitive << ( grp_pool_layer1_fu_511_image_V_address1 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_conv_layer1_out_V_ce0);
    sensitive << ( grp_pool_layer1_fu_511_image_V_ce0 );
    sensitive << ( grp_conv_layer1_fu_519_output_V_ce0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_conv_layer1_out_V_ce1);
    sensitive << ( grp_pool_layer1_fu_511_image_V_ce1 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_conv_layer1_out_V_d0);
    sensitive << ( grp_conv_layer1_fu_519_output_V_d0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_conv_layer1_out_V_we0);
    sensitive << ( grp_conv_layer1_fu_519_output_V_we0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_conv_layer2_out_V_address0);
    sensitive << ( grp_pool_layer2_fu_429_image_V_address0 );
    sensitive << ( grp_conv_layer2_fu_437_output_V_address0 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_conv_layer2_out_V_address1);
    sensitive << ( grp_pool_layer2_fu_429_image_V_address1 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_conv_layer2_out_V_ce0);
    sensitive << ( grp_pool_layer2_fu_429_image_V_ce0 );
    sensitive << ( grp_conv_layer2_fu_437_output_V_ce0 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_conv_layer2_out_V_ce1);
    sensitive << ( grp_pool_layer2_fu_429_image_V_ce1 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_conv_layer2_out_V_d0);
    sensitive << ( grp_conv_layer2_fu_437_output_V_d0 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_conv_layer2_out_V_we0);
    sensitive << ( grp_conv_layer2_fu_437_output_V_we0 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_exitcond5_i_fu_805_p2);
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( i_i1_reg_394 );

    SC_METHOD(thread_exitcond6_i_fu_695_p2);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( i_i7_reg_348 );

    SC_METHOD(thread_exitcond7_i_fu_561_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( i_i_reg_313 );

    SC_METHOD(thread_exitcond_i1_fu_716_p2);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( j_i1_reg_372 );

    SC_METHOD(thread_exitcond_i2_fu_826_p2);
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( j_i2_reg_418 );

    SC_METHOD(thread_exitcond_i_fu_582_p2);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( j_i_reg_337 );

    SC_METHOD(thread_fc_layer1_out_V_address0);
    sensitive << ( fc_layer1_out_V_addr_reg_970 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( tmp_i1_fu_728_p1 );

    SC_METHOD(thread_fc_layer1_out_V_ce0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_fc_layer1_out_V_d0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( p_Val2_s_reg_324 );
    sensitive << ( a_V_i_i_cast_fu_690_p1 );

    SC_METHOD(thread_fc_layer1_out_V_we0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state14 );

    SC_METHOD(thread_fc_layer1_weights_V_address0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( tmp_3_cast_fu_634_p1 );

    SC_METHOD(thread_fc_layer1_weights_V_ce0);
    sensitive << ( ap_CS_fsm_state10 );

    SC_METHOD(thread_fc_layer2_out_V_address0);
    sensitive << ( fc_layer2_out_V_addr_reg_1026 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( tmp_i2_fu_838_p1 );

    SC_METHOD(thread_fc_layer2_out_V_ce0);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_fc_layer2_out_V_d0);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( p_Val2_3_reg_359 );
    sensitive << ( a_V_i_i1_cast_fu_800_p1 );

    SC_METHOD(thread_fc_layer2_out_V_we0);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( ap_CS_fsm_state20 );

    SC_METHOD(thread_fc_layer2_weights_V_address0);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( tmp_5_cast_fu_744_p1 );

    SC_METHOD(thread_fc_layer2_weights_V_ce0);
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_fc_layer3_out_V_address0);
    sensitive << ( fc_layer3_out_V_addr_reg_1087 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state26 );

    SC_METHOD(thread_fc_layer3_out_V_ce0);
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state26 );

    SC_METHOD(thread_fc_layer3_out_V_d0);
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( p_Val2_6_reg_405 );
    sensitive << ( a_V_i_i2_cast_fu_940_p1 );

    SC_METHOD(thread_fc_layer3_out_V_we0);
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( ap_CS_fsm_state26 );

    SC_METHOD(thread_fc_layer3_weights_V_address0);
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( tmp_9_cast_fu_878_p1 );

    SC_METHOD(thread_fc_layer3_weights_V_ce0);
    sensitive << ( ap_CS_fsm_state22 );

    SC_METHOD(thread_grp_conv_layer1_fu_519_ap_start);
    sensitive << ( ap_reg_grp_conv_layer1_fu_519_ap_start );

    SC_METHOD(thread_grp_conv_layer2_fu_437_ap_start);
    sensitive << ( ap_reg_grp_conv_layer2_fu_437_ap_start );

    SC_METHOD(thread_grp_pool_layer1_fu_511_ap_start);
    sensitive << ( ap_reg_grp_pool_layer1_fu_511_ap_start );

    SC_METHOD(thread_grp_pool_layer2_fu_429_ap_start);
    sensitive << ( ap_reg_grp_pool_layer2_fu_429_ap_start );

    SC_METHOD(thread_i_3_fu_701_p2);
    sensitive << ( i_i7_reg_348 );

    SC_METHOD(thread_i_4_fu_811_p2);
    sensitive << ( i_i1_reg_394 );

    SC_METHOD(thread_i_fu_567_p2);
    sensitive << ( i_i_reg_313 );

    SC_METHOD(thread_j_3_fu_722_p2);
    sensitive << ( j_i1_reg_372 );

    SC_METHOD(thread_j_4_fu_832_p2);
    sensitive << ( j_i2_reg_418 );

    SC_METHOD(thread_j_fu_588_p2);
    sensitive << ( j_i_reg_337 );

    SC_METHOD(thread_next_mul_fu_733_p2);
    sensitive << ( phi_mul_reg_383 );

    SC_METHOD(thread_p_Val2_2_fu_656_p2);
    sensitive << ( tmp_18_i_cast_fu_653_p1 );
    sensitive << ( tmp_17_i_fu_645_p3 );

    SC_METHOD(thread_p_Val2_5_fu_766_p2);
    sensitive << ( tmp_13_i_cast_fu_763_p1 );
    sensitive << ( tmp_12_i_fu_755_p3 );

    SC_METHOD(thread_p_Val2_7_fu_889_p0);
    sensitive << ( fc_layer2_out_V_load_reg_1115 );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_p_Val2_7_fu_889_p1);
    sensitive << ( fc_layer3_weights_V_1_reg_1110 );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_p_Val2_7_fu_889_p2);
    sensitive << ( p_Val2_7_fu_889_p0 );
    sensitive << ( p_Val2_7_fu_889_p1 );

    SC_METHOD(thread_p_Val2_8_fu_906_p2);
    sensitive << ( tmp_8_i_cast_fu_903_p1 );
    sensitive << ( tmp_7_i_fu_895_p3 );

    SC_METHOD(thread_p_shl1_cast_fu_619_p1);
    sensitive << ( tmp_1_fu_611_p3 );

    SC_METHOD(thread_p_shl2_cast_fu_851_p1);
    sensitive << ( tmp_6_fu_843_p3 );

    SC_METHOD(thread_p_shl3_cast_fu_863_p1);
    sensitive << ( tmp_7_fu_855_p3 );

    SC_METHOD(thread_p_shl_cast_fu_607_p1);
    sensitive << ( tmp_fu_599_p3 );

    SC_METHOD(thread_pool_layer1_out_V_address0);
    sensitive << ( grp_conv_layer2_fu_437_image_V_address0 );
    sensitive << ( grp_pool_layer1_fu_511_output_V_address0 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_pool_layer1_out_V_address1);
    sensitive << ( grp_conv_layer2_fu_437_image_V_address1 );
    sensitive << ( grp_pool_layer1_fu_511_output_V_address1 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_pool_layer1_out_V_ce0);
    sensitive << ( grp_conv_layer2_fu_437_image_V_ce0 );
    sensitive << ( grp_pool_layer1_fu_511_output_V_ce0 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_pool_layer1_out_V_ce1);
    sensitive << ( grp_conv_layer2_fu_437_image_V_ce1 );
    sensitive << ( grp_pool_layer1_fu_511_output_V_ce1 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_pool_layer1_out_V_d0);
    sensitive << ( grp_pool_layer1_fu_511_output_V_d0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_pool_layer1_out_V_d1);
    sensitive << ( grp_pool_layer1_fu_511_output_V_d1 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_pool_layer1_out_V_we0);
    sensitive << ( grp_pool_layer1_fu_511_output_V_we0 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_pool_layer1_out_V_we1);
    sensitive << ( grp_pool_layer1_fu_511_output_V_we1 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_pool_layer2_out_V_address0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( grp_pool_layer2_fu_429_output_V_address0 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_i_21_fu_594_p1 );

    SC_METHOD(thread_pool_layer2_out_V_address1);
    sensitive << ( grp_pool_layer2_fu_429_output_V_address1 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_pool_layer2_out_V_ce0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( grp_pool_layer2_fu_429_output_V_ce0 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_pool_layer2_out_V_ce1);
    sensitive << ( grp_pool_layer2_fu_429_output_V_ce1 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_pool_layer2_out_V_d0);
    sensitive << ( grp_pool_layer2_fu_429_output_V_d0 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_pool_layer2_out_V_d1);
    sensitive << ( grp_pool_layer2_fu_429_output_V_d1 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_pool_layer2_out_V_we0);
    sensitive << ( grp_pool_layer2_fu_429_output_V_we0 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_pool_layer2_out_V_we1);
    sensitive << ( grp_pool_layer2_fu_429_output_V_we1 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_tmp_10_fu_782_p1);
    sensitive << ( p_Val2_3_reg_359 );

    SC_METHOD(thread_tmp_11_fu_922_p1);
    sensitive << ( p_Val2_6_reg_405 );

    SC_METHOD(thread_tmp_12_i_fu_755_p3);
    sensitive << ( p_Val2_3_reg_359 );

    SC_METHOD(thread_tmp_13_i_cast_fu_763_p1);
    sensitive << ( p_Val2_4_reg_1064 );

    SC_METHOD(thread_tmp_17_i_fu_645_p3);
    sensitive << ( p_Val2_s_reg_324 );

    SC_METHOD(thread_tmp_18_i_cast_fu_653_p1);
    sensitive << ( p_Val2_1_reg_1003 );

    SC_METHOD(thread_tmp_1_fu_611_p3);
    sensitive << ( j_i_reg_337 );

    SC_METHOD(thread_tmp_2_fu_623_p2);
    sensitive << ( p_shl_cast_fu_607_p1 );
    sensitive << ( p_shl1_cast_fu_619_p1 );

    SC_METHOD(thread_tmp_3_cast_fu_634_p1);
    sensitive << ( tmp_3_fu_629_p2 );

    SC_METHOD(thread_tmp_3_fu_629_p2);
    sensitive << ( tmp_i_cast_reg_965 );
    sensitive << ( tmp_2_fu_623_p2 );

    SC_METHOD(thread_tmp_4_fu_672_p1);
    sensitive << ( p_Val2_s_reg_324 );

    SC_METHOD(thread_tmp_5_cast_fu_744_p1);
    sensitive << ( tmp_5_fu_739_p2 );

    SC_METHOD(thread_tmp_5_fu_739_p2);
    sensitive << ( tmp_i9_cast_reg_1021 );
    sensitive << ( phi_mul_reg_383 );

    SC_METHOD(thread_tmp_6_fu_843_p3);
    sensitive << ( j_i2_reg_418 );

    SC_METHOD(thread_tmp_7_fu_855_p3);
    sensitive << ( j_i2_reg_418 );

    SC_METHOD(thread_tmp_7_i_fu_895_p3);
    sensitive << ( p_Val2_6_reg_405 );

    SC_METHOD(thread_tmp_8_fu_867_p2);
    sensitive << ( p_shl3_cast_fu_863_p1 );
    sensitive << ( p_shl2_cast_fu_851_p1 );

    SC_METHOD(thread_tmp_8_i_cast_fu_903_p1);
    sensitive << ( p_Val2_7_reg_1120 );

    SC_METHOD(thread_tmp_9_cast_fu_878_p1);
    sensitive << ( tmp_9_fu_873_p2 );

    SC_METHOD(thread_tmp_9_fu_873_p2);
    sensitive << ( tmp_i1_cast_reg_1082 );
    sensitive << ( tmp_8_fu_867_p2 );

    SC_METHOD(thread_tmp_fu_599_p3);
    sensitive << ( j_i_reg_337 );

    SC_METHOD(thread_tmp_i1_27_fu_817_p1);
    sensitive << ( i_i1_reg_394 );

    SC_METHOD(thread_tmp_i1_cast_fu_822_p1);
    sensitive << ( i_i1_reg_394 );

    SC_METHOD(thread_tmp_i1_fu_728_p1);
    sensitive << ( j_i1_reg_372 );

    SC_METHOD(thread_tmp_i2_fu_838_p1);
    sensitive << ( j_i2_reg_418 );

    SC_METHOD(thread_tmp_i9_cast_fu_712_p1);
    sensitive << ( i_i7_reg_348 );

    SC_METHOD(thread_tmp_i9_fu_707_p1);
    sensitive << ( i_i7_reg_348 );

    SC_METHOD(thread_tmp_i_21_fu_594_p1);
    sensitive << ( j_i_reg_337 );

    SC_METHOD(thread_tmp_i_cast_fu_578_p1);
    sensitive << ( i_i_reg_313 );

    SC_METHOD(thread_tmp_i_fu_573_p1);
    sensitive << ( i_i_reg_313 );

    SC_METHOD(thread_tmp_i_i1_fu_786_p2);
    sensitive << ( ap_CS_fsm_state20 );
    sensitive << ( p_Val2_3_reg_359 );

    SC_METHOD(thread_tmp_i_i2_fu_926_p2);
    sensitive << ( ap_CS_fsm_state26 );
    sensitive << ( p_Val2_6_reg_405 );

    SC_METHOD(thread_tmp_i_i_fu_676_p2);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( p_Val2_s_reg_324 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( exitcond7_i_fu_561_p2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( exitcond_i_fu_582_p2 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( exitcond6_i_fu_695_p2 );
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( exitcond_i1_fu_716_p2 );
    sensitive << ( ap_CS_fsm_state21 );
    sensitive << ( exitcond5_i_fu_805_p2 );
    sensitive << ( ap_CS_fsm_state22 );
    sensitive << ( exitcond_i2_fu_826_p2 );
    sensitive << ( grp_pool_layer2_fu_429_ap_done );
    sensitive << ( grp_conv_layer2_fu_437_ap_done );
    sensitive << ( grp_pool_layer1_fu_511_ap_done );
    sensitive << ( grp_conv_layer1_fu_519_ap_done );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "00000000000000000000000001";
    ap_reg_grp_pool_layer2_fu_429_ap_start = SC_LOGIC_0;
    ap_reg_grp_conv_layer2_fu_437_ap_start = SC_LOGIC_0;
    ap_reg_grp_pool_layer1_fu_511_ap_start = SC_LOGIC_0;
    ap_reg_grp_conv_layer1_fu_519_ap_start = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "nnet_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, conv_layer1_out_V_address0, "(port)conv_layer1_out_V_address0");
    sc_trace(mVcdFile, conv_layer1_out_V_ce0, "(port)conv_layer1_out_V_ce0");
    sc_trace(mVcdFile, conv_layer1_out_V_we0, "(port)conv_layer1_out_V_we0");
    sc_trace(mVcdFile, conv_layer1_out_V_d0, "(port)conv_layer1_out_V_d0");
    sc_trace(mVcdFile, conv_layer1_out_V_q0, "(port)conv_layer1_out_V_q0");
    sc_trace(mVcdFile, conv_layer1_out_V_address1, "(port)conv_layer1_out_V_address1");
    sc_trace(mVcdFile, conv_layer1_out_V_ce1, "(port)conv_layer1_out_V_ce1");
    sc_trace(mVcdFile, conv_layer1_out_V_q1, "(port)conv_layer1_out_V_q1");
    sc_trace(mVcdFile, conv_layer2_out_V_address0, "(port)conv_layer2_out_V_address0");
    sc_trace(mVcdFile, conv_layer2_out_V_ce0, "(port)conv_layer2_out_V_ce0");
    sc_trace(mVcdFile, conv_layer2_out_V_we0, "(port)conv_layer2_out_V_we0");
    sc_trace(mVcdFile, conv_layer2_out_V_d0, "(port)conv_layer2_out_V_d0");
    sc_trace(mVcdFile, conv_layer2_out_V_q0, "(port)conv_layer2_out_V_q0");
    sc_trace(mVcdFile, conv_layer2_out_V_address1, "(port)conv_layer2_out_V_address1");
    sc_trace(mVcdFile, conv_layer2_out_V_ce1, "(port)conv_layer2_out_V_ce1");
    sc_trace(mVcdFile, conv_layer2_out_V_q1, "(port)conv_layer2_out_V_q1");
    sc_trace(mVcdFile, pool_layer1_out_V_address0, "(port)pool_layer1_out_V_address0");
    sc_trace(mVcdFile, pool_layer1_out_V_ce0, "(port)pool_layer1_out_V_ce0");
    sc_trace(mVcdFile, pool_layer1_out_V_we0, "(port)pool_layer1_out_V_we0");
    sc_trace(mVcdFile, pool_layer1_out_V_d0, "(port)pool_layer1_out_V_d0");
    sc_trace(mVcdFile, pool_layer1_out_V_q0, "(port)pool_layer1_out_V_q0");
    sc_trace(mVcdFile, pool_layer1_out_V_address1, "(port)pool_layer1_out_V_address1");
    sc_trace(mVcdFile, pool_layer1_out_V_ce1, "(port)pool_layer1_out_V_ce1");
    sc_trace(mVcdFile, pool_layer1_out_V_we1, "(port)pool_layer1_out_V_we1");
    sc_trace(mVcdFile, pool_layer1_out_V_d1, "(port)pool_layer1_out_V_d1");
    sc_trace(mVcdFile, pool_layer1_out_V_q1, "(port)pool_layer1_out_V_q1");
    sc_trace(mVcdFile, pool_layer2_out_V_address0, "(port)pool_layer2_out_V_address0");
    sc_trace(mVcdFile, pool_layer2_out_V_ce0, "(port)pool_layer2_out_V_ce0");
    sc_trace(mVcdFile, pool_layer2_out_V_we0, "(port)pool_layer2_out_V_we0");
    sc_trace(mVcdFile, pool_layer2_out_V_d0, "(port)pool_layer2_out_V_d0");
    sc_trace(mVcdFile, pool_layer2_out_V_q0, "(port)pool_layer2_out_V_q0");
    sc_trace(mVcdFile, pool_layer2_out_V_address1, "(port)pool_layer2_out_V_address1");
    sc_trace(mVcdFile, pool_layer2_out_V_ce1, "(port)pool_layer2_out_V_ce1");
    sc_trace(mVcdFile, pool_layer2_out_V_we1, "(port)pool_layer2_out_V_we1");
    sc_trace(mVcdFile, pool_layer2_out_V_d1, "(port)pool_layer2_out_V_d1");
    sc_trace(mVcdFile, fc_layer1_out_V_address0, "(port)fc_layer1_out_V_address0");
    sc_trace(mVcdFile, fc_layer1_out_V_ce0, "(port)fc_layer1_out_V_ce0");
    sc_trace(mVcdFile, fc_layer1_out_V_we0, "(port)fc_layer1_out_V_we0");
    sc_trace(mVcdFile, fc_layer1_out_V_d0, "(port)fc_layer1_out_V_d0");
    sc_trace(mVcdFile, fc_layer1_out_V_q0, "(port)fc_layer1_out_V_q0");
    sc_trace(mVcdFile, fc_layer2_out_V_address0, "(port)fc_layer2_out_V_address0");
    sc_trace(mVcdFile, fc_layer2_out_V_ce0, "(port)fc_layer2_out_V_ce0");
    sc_trace(mVcdFile, fc_layer2_out_V_we0, "(port)fc_layer2_out_V_we0");
    sc_trace(mVcdFile, fc_layer2_out_V_d0, "(port)fc_layer2_out_V_d0");
    sc_trace(mVcdFile, fc_layer2_out_V_q0, "(port)fc_layer2_out_V_q0");
    sc_trace(mVcdFile, fc_layer3_out_V_address0, "(port)fc_layer3_out_V_address0");
    sc_trace(mVcdFile, fc_layer3_out_V_ce0, "(port)fc_layer3_out_V_ce0");
    sc_trace(mVcdFile, fc_layer3_out_V_we0, "(port)fc_layer3_out_V_we0");
    sc_trace(mVcdFile, fc_layer3_out_V_d0, "(port)fc_layer3_out_V_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, fc_layer1_weights_V_address0, "fc_layer1_weights_V_address0");
    sc_trace(mVcdFile, fc_layer1_weights_V_ce0, "fc_layer1_weights_V_ce0");
    sc_trace(mVcdFile, fc_layer1_weights_V_q0, "fc_layer1_weights_V_q0");
    sc_trace(mVcdFile, fc_layer2_weights_V_address0, "fc_layer2_weights_V_address0");
    sc_trace(mVcdFile, fc_layer2_weights_V_ce0, "fc_layer2_weights_V_ce0");
    sc_trace(mVcdFile, fc_layer2_weights_V_q0, "fc_layer2_weights_V_q0");
    sc_trace(mVcdFile, fc_layer3_weights_V_address0, "fc_layer3_weights_V_address0");
    sc_trace(mVcdFile, fc_layer3_weights_V_ce0, "fc_layer3_weights_V_ce0");
    sc_trace(mVcdFile, fc_layer3_weights_V_q0, "fc_layer3_weights_V_q0");
    sc_trace(mVcdFile, i_fu_567_p2, "i_fu_567_p2");
    sc_trace(mVcdFile, i_reg_960, "i_reg_960");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, tmp_i_cast_fu_578_p1, "tmp_i_cast_fu_578_p1");
    sc_trace(mVcdFile, tmp_i_cast_reg_965, "tmp_i_cast_reg_965");
    sc_trace(mVcdFile, exitcond7_i_fu_561_p2, "exitcond7_i_fu_561_p2");
    sc_trace(mVcdFile, fc_layer1_out_V_addr_reg_970, "fc_layer1_out_V_addr_reg_970");
    sc_trace(mVcdFile, j_fu_588_p2, "j_fu_588_p2");
    sc_trace(mVcdFile, j_reg_978, "j_reg_978");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, exitcond_i_fu_582_p2, "exitcond_i_fu_582_p2");
    sc_trace(mVcdFile, fc_layer1_weights_V_1_reg_993, "fc_layer1_weights_V_1_reg_993");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, pool_layer2_out_V_lo_reg_998, "pool_layer2_out_V_lo_reg_998");
    sc_trace(mVcdFile, p_Val2_1_fu_945_p2, "p_Val2_1_fu_945_p2");
    sc_trace(mVcdFile, p_Val2_1_reg_1003, "p_Val2_1_reg_1003");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, i_3_fu_701_p2, "i_3_fu_701_p2");
    sc_trace(mVcdFile, i_3_reg_1016, "i_3_reg_1016");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, tmp_i9_cast_fu_712_p1, "tmp_i9_cast_fu_712_p1");
    sc_trace(mVcdFile, tmp_i9_cast_reg_1021, "tmp_i9_cast_reg_1021");
    sc_trace(mVcdFile, exitcond6_i_fu_695_p2, "exitcond6_i_fu_695_p2");
    sc_trace(mVcdFile, fc_layer2_out_V_addr_reg_1026, "fc_layer2_out_V_addr_reg_1026");
    sc_trace(mVcdFile, j_3_fu_722_p2, "j_3_fu_722_p2");
    sc_trace(mVcdFile, j_3_reg_1034, "j_3_reg_1034");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, next_mul_fu_733_p2, "next_mul_fu_733_p2");
    sc_trace(mVcdFile, next_mul_reg_1039, "next_mul_reg_1039");
    sc_trace(mVcdFile, exitcond_i1_fu_716_p2, "exitcond_i1_fu_716_p2");
    sc_trace(mVcdFile, fc_layer2_weights_V_1_reg_1054, "fc_layer2_weights_V_1_reg_1054");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, fc_layer1_out_V_load_reg_1059, "fc_layer1_out_V_load_reg_1059");
    sc_trace(mVcdFile, p_Val2_4_fu_951_p2, "p_Val2_4_fu_951_p2");
    sc_trace(mVcdFile, p_Val2_4_reg_1064, "p_Val2_4_reg_1064");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, i_4_fu_811_p2, "i_4_fu_811_p2");
    sc_trace(mVcdFile, i_4_reg_1077, "i_4_reg_1077");
    sc_trace(mVcdFile, ap_CS_fsm_state21, "ap_CS_fsm_state21");
    sc_trace(mVcdFile, tmp_i1_cast_fu_822_p1, "tmp_i1_cast_fu_822_p1");
    sc_trace(mVcdFile, tmp_i1_cast_reg_1082, "tmp_i1_cast_reg_1082");
    sc_trace(mVcdFile, exitcond5_i_fu_805_p2, "exitcond5_i_fu_805_p2");
    sc_trace(mVcdFile, fc_layer3_out_V_addr_reg_1087, "fc_layer3_out_V_addr_reg_1087");
    sc_trace(mVcdFile, j_4_fu_832_p2, "j_4_fu_832_p2");
    sc_trace(mVcdFile, j_4_reg_1095, "j_4_reg_1095");
    sc_trace(mVcdFile, ap_CS_fsm_state22, "ap_CS_fsm_state22");
    sc_trace(mVcdFile, exitcond_i2_fu_826_p2, "exitcond_i2_fu_826_p2");
    sc_trace(mVcdFile, fc_layer3_weights_V_1_reg_1110, "fc_layer3_weights_V_1_reg_1110");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, fc_layer2_out_V_load_reg_1115, "fc_layer2_out_V_load_reg_1115");
    sc_trace(mVcdFile, p_Val2_7_fu_889_p2, "p_Val2_7_fu_889_p2");
    sc_trace(mVcdFile, p_Val2_7_reg_1120, "p_Val2_7_reg_1120");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, ap_CS_fsm_state25, "ap_CS_fsm_state25");
    sc_trace(mVcdFile, grp_pool_layer2_fu_429_ap_start, "grp_pool_layer2_fu_429_ap_start");
    sc_trace(mVcdFile, grp_pool_layer2_fu_429_ap_done, "grp_pool_layer2_fu_429_ap_done");
    sc_trace(mVcdFile, grp_pool_layer2_fu_429_ap_idle, "grp_pool_layer2_fu_429_ap_idle");
    sc_trace(mVcdFile, grp_pool_layer2_fu_429_ap_ready, "grp_pool_layer2_fu_429_ap_ready");
    sc_trace(mVcdFile, grp_pool_layer2_fu_429_output_V_address0, "grp_pool_layer2_fu_429_output_V_address0");
    sc_trace(mVcdFile, grp_pool_layer2_fu_429_output_V_ce0, "grp_pool_layer2_fu_429_output_V_ce0");
    sc_trace(mVcdFile, grp_pool_layer2_fu_429_output_V_we0, "grp_pool_layer2_fu_429_output_V_we0");
    sc_trace(mVcdFile, grp_pool_layer2_fu_429_output_V_d0, "grp_pool_layer2_fu_429_output_V_d0");
    sc_trace(mVcdFile, grp_pool_layer2_fu_429_output_V_address1, "grp_pool_layer2_fu_429_output_V_address1");
    sc_trace(mVcdFile, grp_pool_layer2_fu_429_output_V_ce1, "grp_pool_layer2_fu_429_output_V_ce1");
    sc_trace(mVcdFile, grp_pool_layer2_fu_429_output_V_we1, "grp_pool_layer2_fu_429_output_V_we1");
    sc_trace(mVcdFile, grp_pool_layer2_fu_429_output_V_d1, "grp_pool_layer2_fu_429_output_V_d1");
    sc_trace(mVcdFile, grp_pool_layer2_fu_429_image_V_address0, "grp_pool_layer2_fu_429_image_V_address0");
    sc_trace(mVcdFile, grp_pool_layer2_fu_429_image_V_ce0, "grp_pool_layer2_fu_429_image_V_ce0");
    sc_trace(mVcdFile, grp_pool_layer2_fu_429_image_V_address1, "grp_pool_layer2_fu_429_image_V_address1");
    sc_trace(mVcdFile, grp_pool_layer2_fu_429_image_V_ce1, "grp_pool_layer2_fu_429_image_V_ce1");
    sc_trace(mVcdFile, grp_conv_layer2_fu_437_ap_start, "grp_conv_layer2_fu_437_ap_start");
    sc_trace(mVcdFile, grp_conv_layer2_fu_437_ap_done, "grp_conv_layer2_fu_437_ap_done");
    sc_trace(mVcdFile, grp_conv_layer2_fu_437_ap_idle, "grp_conv_layer2_fu_437_ap_idle");
    sc_trace(mVcdFile, grp_conv_layer2_fu_437_ap_ready, "grp_conv_layer2_fu_437_ap_ready");
    sc_trace(mVcdFile, grp_conv_layer2_fu_437_output_V_address0, "grp_conv_layer2_fu_437_output_V_address0");
    sc_trace(mVcdFile, grp_conv_layer2_fu_437_output_V_ce0, "grp_conv_layer2_fu_437_output_V_ce0");
    sc_trace(mVcdFile, grp_conv_layer2_fu_437_output_V_we0, "grp_conv_layer2_fu_437_output_V_we0");
    sc_trace(mVcdFile, grp_conv_layer2_fu_437_output_V_d0, "grp_conv_layer2_fu_437_output_V_d0");
    sc_trace(mVcdFile, grp_conv_layer2_fu_437_image_V_address0, "grp_conv_layer2_fu_437_image_V_address0");
    sc_trace(mVcdFile, grp_conv_layer2_fu_437_image_V_ce0, "grp_conv_layer2_fu_437_image_V_ce0");
    sc_trace(mVcdFile, grp_conv_layer2_fu_437_image_V_address1, "grp_conv_layer2_fu_437_image_V_address1");
    sc_trace(mVcdFile, grp_conv_layer2_fu_437_image_V_ce1, "grp_conv_layer2_fu_437_image_V_ce1");
    sc_trace(mVcdFile, grp_pool_layer1_fu_511_ap_start, "grp_pool_layer1_fu_511_ap_start");
    sc_trace(mVcdFile, grp_pool_layer1_fu_511_ap_done, "grp_pool_layer1_fu_511_ap_done");
    sc_trace(mVcdFile, grp_pool_layer1_fu_511_ap_idle, "grp_pool_layer1_fu_511_ap_idle");
    sc_trace(mVcdFile, grp_pool_layer1_fu_511_ap_ready, "grp_pool_layer1_fu_511_ap_ready");
    sc_trace(mVcdFile, grp_pool_layer1_fu_511_output_V_address0, "grp_pool_layer1_fu_511_output_V_address0");
    sc_trace(mVcdFile, grp_pool_layer1_fu_511_output_V_ce0, "grp_pool_layer1_fu_511_output_V_ce0");
    sc_trace(mVcdFile, grp_pool_layer1_fu_511_output_V_we0, "grp_pool_layer1_fu_511_output_V_we0");
    sc_trace(mVcdFile, grp_pool_layer1_fu_511_output_V_d0, "grp_pool_layer1_fu_511_output_V_d0");
    sc_trace(mVcdFile, grp_pool_layer1_fu_511_output_V_address1, "grp_pool_layer1_fu_511_output_V_address1");
    sc_trace(mVcdFile, grp_pool_layer1_fu_511_output_V_ce1, "grp_pool_layer1_fu_511_output_V_ce1");
    sc_trace(mVcdFile, grp_pool_layer1_fu_511_output_V_we1, "grp_pool_layer1_fu_511_output_V_we1");
    sc_trace(mVcdFile, grp_pool_layer1_fu_511_output_V_d1, "grp_pool_layer1_fu_511_output_V_d1");
    sc_trace(mVcdFile, grp_pool_layer1_fu_511_image_V_address0, "grp_pool_layer1_fu_511_image_V_address0");
    sc_trace(mVcdFile, grp_pool_layer1_fu_511_image_V_ce0, "grp_pool_layer1_fu_511_image_V_ce0");
    sc_trace(mVcdFile, grp_pool_layer1_fu_511_image_V_address1, "grp_pool_layer1_fu_511_image_V_address1");
    sc_trace(mVcdFile, grp_pool_layer1_fu_511_image_V_ce1, "grp_pool_layer1_fu_511_image_V_ce1");
    sc_trace(mVcdFile, grp_conv_layer1_fu_519_ap_start, "grp_conv_layer1_fu_519_ap_start");
    sc_trace(mVcdFile, grp_conv_layer1_fu_519_ap_done, "grp_conv_layer1_fu_519_ap_done");
    sc_trace(mVcdFile, grp_conv_layer1_fu_519_ap_idle, "grp_conv_layer1_fu_519_ap_idle");
    sc_trace(mVcdFile, grp_conv_layer1_fu_519_ap_ready, "grp_conv_layer1_fu_519_ap_ready");
    sc_trace(mVcdFile, grp_conv_layer1_fu_519_output_V_address0, "grp_conv_layer1_fu_519_output_V_address0");
    sc_trace(mVcdFile, grp_conv_layer1_fu_519_output_V_ce0, "grp_conv_layer1_fu_519_output_V_ce0");
    sc_trace(mVcdFile, grp_conv_layer1_fu_519_output_V_we0, "grp_conv_layer1_fu_519_output_V_we0");
    sc_trace(mVcdFile, grp_conv_layer1_fu_519_output_V_d0, "grp_conv_layer1_fu_519_output_V_d0");
    sc_trace(mVcdFile, i_i_reg_313, "i_i_reg_313");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, p_Val2_s_reg_324, "p_Val2_s_reg_324");
    sc_trace(mVcdFile, j_i_reg_337, "j_i_reg_337");
    sc_trace(mVcdFile, i_i7_reg_348, "i_i7_reg_348");
    sc_trace(mVcdFile, ap_CS_fsm_state20, "ap_CS_fsm_state20");
    sc_trace(mVcdFile, p_Val2_3_reg_359, "p_Val2_3_reg_359");
    sc_trace(mVcdFile, j_i1_reg_372, "j_i1_reg_372");
    sc_trace(mVcdFile, phi_mul_reg_383, "phi_mul_reg_383");
    sc_trace(mVcdFile, i_i1_reg_394, "i_i1_reg_394");
    sc_trace(mVcdFile, ap_CS_fsm_state26, "ap_CS_fsm_state26");
    sc_trace(mVcdFile, p_Val2_6_reg_405, "p_Val2_6_reg_405");
    sc_trace(mVcdFile, j_i2_reg_418, "j_i2_reg_418");
    sc_trace(mVcdFile, ap_reg_grp_pool_layer2_fu_429_ap_start, "ap_reg_grp_pool_layer2_fu_429_ap_start");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_reg_grp_conv_layer2_fu_437_ap_start, "ap_reg_grp_conv_layer2_fu_437_ap_start");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_reg_grp_pool_layer1_fu_511_ap_start, "ap_reg_grp_pool_layer1_fu_511_ap_start");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_reg_grp_conv_layer1_fu_519_ap_start, "ap_reg_grp_conv_layer1_fu_519_ap_start");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_i_fu_573_p1, "tmp_i_fu_573_p1");
    sc_trace(mVcdFile, tmp_3_cast_fu_634_p1, "tmp_3_cast_fu_634_p1");
    sc_trace(mVcdFile, tmp_i_21_fu_594_p1, "tmp_i_21_fu_594_p1");
    sc_trace(mVcdFile, tmp_i9_fu_707_p1, "tmp_i9_fu_707_p1");
    sc_trace(mVcdFile, tmp_5_cast_fu_744_p1, "tmp_5_cast_fu_744_p1");
    sc_trace(mVcdFile, tmp_i1_fu_728_p1, "tmp_i1_fu_728_p1");
    sc_trace(mVcdFile, tmp_i1_27_fu_817_p1, "tmp_i1_27_fu_817_p1");
    sc_trace(mVcdFile, tmp_9_cast_fu_878_p1, "tmp_9_cast_fu_878_p1");
    sc_trace(mVcdFile, tmp_i2_fu_838_p1, "tmp_i2_fu_838_p1");
    sc_trace(mVcdFile, a_V_i_i_cast_fu_690_p1, "a_V_i_i_cast_fu_690_p1");
    sc_trace(mVcdFile, a_V_i_i1_cast_fu_800_p1, "a_V_i_i1_cast_fu_800_p1");
    sc_trace(mVcdFile, a_V_i_i2_cast_fu_940_p1, "a_V_i_i2_cast_fu_940_p1");
    sc_trace(mVcdFile, tmp_fu_599_p3, "tmp_fu_599_p3");
    sc_trace(mVcdFile, tmp_1_fu_611_p3, "tmp_1_fu_611_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_607_p1, "p_shl_cast_fu_607_p1");
    sc_trace(mVcdFile, p_shl1_cast_fu_619_p1, "p_shl1_cast_fu_619_p1");
    sc_trace(mVcdFile, tmp_2_fu_623_p2, "tmp_2_fu_623_p2");
    sc_trace(mVcdFile, tmp_3_fu_629_p2, "tmp_3_fu_629_p2");
    sc_trace(mVcdFile, tmp_18_i_cast_fu_653_p1, "tmp_18_i_cast_fu_653_p1");
    sc_trace(mVcdFile, tmp_17_i_fu_645_p3, "tmp_17_i_fu_645_p3");
    sc_trace(mVcdFile, p_Val2_2_fu_656_p2, "p_Val2_2_fu_656_p2");
    sc_trace(mVcdFile, tmp_i_i_fu_676_p2, "tmp_i_i_fu_676_p2");
    sc_trace(mVcdFile, tmp_4_fu_672_p1, "tmp_4_fu_672_p1");
    sc_trace(mVcdFile, a_V_i_i_fu_682_p3, "a_V_i_i_fu_682_p3");
    sc_trace(mVcdFile, tmp_5_fu_739_p2, "tmp_5_fu_739_p2");
    sc_trace(mVcdFile, tmp_13_i_cast_fu_763_p1, "tmp_13_i_cast_fu_763_p1");
    sc_trace(mVcdFile, tmp_12_i_fu_755_p3, "tmp_12_i_fu_755_p3");
    sc_trace(mVcdFile, p_Val2_5_fu_766_p2, "p_Val2_5_fu_766_p2");
    sc_trace(mVcdFile, tmp_i_i1_fu_786_p2, "tmp_i_i1_fu_786_p2");
    sc_trace(mVcdFile, tmp_10_fu_782_p1, "tmp_10_fu_782_p1");
    sc_trace(mVcdFile, a_V_i_i1_fu_792_p3, "a_V_i_i1_fu_792_p3");
    sc_trace(mVcdFile, tmp_6_fu_843_p3, "tmp_6_fu_843_p3");
    sc_trace(mVcdFile, tmp_7_fu_855_p3, "tmp_7_fu_855_p3");
    sc_trace(mVcdFile, p_shl3_cast_fu_863_p1, "p_shl3_cast_fu_863_p1");
    sc_trace(mVcdFile, p_shl2_cast_fu_851_p1, "p_shl2_cast_fu_851_p1");
    sc_trace(mVcdFile, tmp_8_fu_867_p2, "tmp_8_fu_867_p2");
    sc_trace(mVcdFile, tmp_9_fu_873_p2, "tmp_9_fu_873_p2");
    sc_trace(mVcdFile, p_Val2_7_fu_889_p0, "p_Val2_7_fu_889_p0");
    sc_trace(mVcdFile, p_Val2_7_fu_889_p1, "p_Val2_7_fu_889_p1");
    sc_trace(mVcdFile, tmp_8_i_cast_fu_903_p1, "tmp_8_i_cast_fu_903_p1");
    sc_trace(mVcdFile, tmp_7_i_fu_895_p3, "tmp_7_i_fu_895_p3");
    sc_trace(mVcdFile, p_Val2_8_fu_906_p2, "p_Val2_8_fu_906_p2");
    sc_trace(mVcdFile, tmp_i_i2_fu_926_p2, "tmp_i_i2_fu_926_p2");
    sc_trace(mVcdFile, tmp_11_fu_922_p1, "tmp_11_fu_922_p1");
    sc_trace(mVcdFile, a_V_i_i2_fu_932_p3, "a_V_i_i2_fu_932_p3");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("nnet.hdltvin.dat");
    mHdltvoutHandle.open("nnet.hdltvout.dat");
}

nnet::~nnet() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete fc_layer1_weights_V_U;
    delete fc_layer2_weights_V_U;
    delete fc_layer3_weights_V_U;
    delete grp_pool_layer2_fu_429;
    delete grp_conv_layer2_fu_437;
    delete grp_pool_layer1_fu_511;
    delete grp_conv_layer1_fu_519;
    delete nnet_mul_mul_24s_4jc_U109;
    delete nnet_mul_mul_24s_5jm_U110;
}

void nnet::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_conv_layer1_fu_519_ap_start = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
             esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_reg_grp_conv_layer1_fu_519_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_conv_layer1_fu_519_ap_ready.read())) {
            ap_reg_grp_conv_layer1_fu_519_ap_start = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_conv_layer2_fu_437_ap_start = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
            ap_reg_grp_conv_layer2_fu_437_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_conv_layer2_fu_437_ap_ready.read())) {
            ap_reg_grp_conv_layer2_fu_437_ap_start = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_pool_layer1_fu_511_ap_start = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
            ap_reg_grp_pool_layer1_fu_511_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_pool_layer1_fu_511_ap_ready.read())) {
            ap_reg_grp_pool_layer1_fu_511_ap_start = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_pool_layer2_fu_429_ap_start = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
            ap_reg_grp_pool_layer2_fu_429_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_pool_layer2_fu_429_ap_ready.read())) {
            ap_reg_grp_pool_layer2_fu_429_ap_start = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
         esl_seteq<1,1,1>(exitcond6_i_fu_695_p2.read(), ap_const_lv1_1))) {
        i_i1_reg_394 = ap_const_lv4_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        i_i1_reg_394 = i_4_reg_1077.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(exitcond7_i_fu_561_p2.read(), ap_const_lv1_1))) {
        i_i7_reg_348 = ap_const_lv7_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        i_i7_reg_348 = i_3_reg_1016.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        i_i_reg_313 = i_reg_960.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
                esl_seteq<1,1,1>(grp_pool_layer2_fu_429_ap_done.read(), ap_const_logic_1))) {
        i_i_reg_313 = ap_const_lv7_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        j_i1_reg_372 = j_3_reg_1034.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_i_fu_695_p2.read()))) {
        j_i1_reg_372 = ap_const_lv7_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        j_i2_reg_418 = j_4_reg_1095.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_i_fu_805_p2.read()))) {
        j_i2_reg_418 = ap_const_lv7_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        j_i_reg_337 = j_reg_978.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
                esl_seteq<1,1,1>(exitcond7_i_fu_561_p2.read(), ap_const_lv1_0))) {
        j_i_reg_337 = ap_const_lv10_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        p_Val2_3_reg_359 = p_Val2_5_fu_766_p2.read().range(43, 20);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_i_fu_695_p2.read()))) {
        p_Val2_3_reg_359 = ap_const_lv24_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state25.read())) {
        p_Val2_6_reg_405 = p_Val2_8_fu_906_p2.read().range(43, 20);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_i_fu_805_p2.read()))) {
        p_Val2_6_reg_405 = ap_const_lv24_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        p_Val2_s_reg_324 = p_Val2_2_fu_656_p2.read().range(43, 20);
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
                esl_seteq<1,1,1>(exitcond7_i_fu_561_p2.read(), ap_const_lv1_0))) {
        p_Val2_s_reg_324 = ap_const_lv24_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state19.read())) {
        phi_mul_reg_383 = next_mul_reg_1039.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_i_fu_695_p2.read()))) {
        phi_mul_reg_383 = ap_const_lv14_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(exitcond7_i_fu_561_p2.read(), ap_const_lv1_0))) {
        fc_layer1_out_V_addr_reg_970 =  (sc_lv<7>) (tmp_i_fu_573_p1.read());
        tmp_i_cast_reg_965 = tmp_i_cast_fu_578_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        fc_layer1_out_V_load_reg_1059 = fc_layer1_out_V_q0.read();
        fc_layer2_weights_V_1_reg_1054 = fc_layer2_weights_V_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        fc_layer1_weights_V_1_reg_993 = fc_layer1_weights_V_q0.read();
        pool_layer2_out_V_lo_reg_998 = pool_layer2_out_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond6_i_fu_695_p2.read()))) {
        fc_layer2_out_V_addr_reg_1026 =  (sc_lv<7>) (tmp_i9_fu_707_p1.read());
        tmp_i9_cast_reg_1021 = tmp_i9_cast_fu_712_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state23.read())) {
        fc_layer2_out_V_load_reg_1115 = fc_layer2_out_V_q0.read();
        fc_layer3_weights_V_1_reg_1110 = fc_layer3_weights_V_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond5_i_fu_805_p2.read()))) {
        fc_layer3_out_V_addr_reg_1087 =  (sc_lv<4>) (tmp_i1_27_fu_817_p1.read());
        tmp_i1_cast_reg_1082 = tmp_i1_cast_fu_822_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        i_3_reg_1016 = i_3_fu_701_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read())) {
        i_4_reg_1077 = i_4_fu_811_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        i_reg_960 = i_fu_567_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        j_3_reg_1034 = j_3_fu_722_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        j_4_reg_1095 = j_4_fu_832_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        j_reg_978 = j_fu_588_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_i1_fu_716_p2.read()))) {
        next_mul_reg_1039 = next_mul_fu_733_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        p_Val2_1_reg_1003 = p_Val2_1_fu_945_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        p_Val2_4_reg_1064 = p_Val2_4_fu_951_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state24.read())) {
        p_Val2_7_reg_1120 = p_Val2_7_fu_889_p2.read();
    }
}

void nnet::thread_a_V_i_i1_cast_fu_800_p1() {
    a_V_i_i1_cast_fu_800_p1 = esl_zext<24,23>(a_V_i_i1_fu_792_p3.read());
}

void nnet::thread_a_V_i_i1_fu_792_p3() {
    a_V_i_i1_fu_792_p3 = (!tmp_i_i1_fu_786_p2.read()[0].is_01())? sc_lv<23>(): ((tmp_i_i1_fu_786_p2.read()[0].to_bool())? tmp_10_fu_782_p1.read(): ap_const_lv23_0);
}

void nnet::thread_a_V_i_i2_cast_fu_940_p1() {
    a_V_i_i2_cast_fu_940_p1 = esl_zext<24,23>(a_V_i_i2_fu_932_p3.read());
}

void nnet::thread_a_V_i_i2_fu_932_p3() {
    a_V_i_i2_fu_932_p3 = (!tmp_i_i2_fu_926_p2.read()[0].is_01())? sc_lv<23>(): ((tmp_i_i2_fu_926_p2.read()[0].to_bool())? tmp_11_fu_922_p1.read(): ap_const_lv23_0);
}

void nnet::thread_a_V_i_i_cast_fu_690_p1() {
    a_V_i_i_cast_fu_690_p1 = esl_zext<24,23>(a_V_i_i_fu_682_p3.read());
}

void nnet::thread_a_V_i_i_fu_682_p3() {
    a_V_i_i_fu_682_p3 = (!tmp_i_i_fu_676_p2.read()[0].is_01())? sc_lv<23>(): ((tmp_i_i_fu_676_p2.read()[0].to_bool())? tmp_4_fu_672_p1.read(): ap_const_lv23_0);
}

void nnet::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void nnet::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void nnet::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void nnet::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void nnet::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void nnet::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void nnet::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void nnet::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void nnet::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void nnet::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void nnet::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read()[18];
}

void nnet::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void nnet::thread_ap_CS_fsm_state20() {
    ap_CS_fsm_state20 = ap_CS_fsm.read()[19];
}

void nnet::thread_ap_CS_fsm_state21() {
    ap_CS_fsm_state21 = ap_CS_fsm.read()[20];
}

void nnet::thread_ap_CS_fsm_state22() {
    ap_CS_fsm_state22 = ap_CS_fsm.read()[21];
}

void nnet::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read()[22];
}

void nnet::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read()[23];
}

void nnet::thread_ap_CS_fsm_state25() {
    ap_CS_fsm_state25 = ap_CS_fsm.read()[24];
}

void nnet::thread_ap_CS_fsm_state26() {
    ap_CS_fsm_state26 = ap_CS_fsm.read()[25];
}

void nnet::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void nnet::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void nnet::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void nnet::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void nnet::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void nnet::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void nnet::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void nnet::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) && 
         esl_seteq<1,1,1>(exitcond5_i_fu_805_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void nnet::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void nnet::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) && 
         esl_seteq<1,1,1>(exitcond5_i_fu_805_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void nnet::thread_conv_layer1_out_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        conv_layer1_out_V_address0 = grp_conv_layer1_fu_519_output_V_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        conv_layer1_out_V_address0 = grp_pool_layer1_fu_511_image_V_address0.read();
    } else {
        conv_layer1_out_V_address0 = "XXXXXXXXXXXXX";
    }
}

void nnet::thread_conv_layer1_out_V_address1() {
    conv_layer1_out_V_address1 = grp_pool_layer1_fu_511_image_V_address1.read();
}

void nnet::thread_conv_layer1_out_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        conv_layer1_out_V_ce0 = grp_conv_layer1_fu_519_output_V_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        conv_layer1_out_V_ce0 = grp_pool_layer1_fu_511_image_V_ce0.read();
    } else {
        conv_layer1_out_V_ce0 = ap_const_logic_0;
    }
}

void nnet::thread_conv_layer1_out_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        conv_layer1_out_V_ce1 = grp_pool_layer1_fu_511_image_V_ce1.read();
    } else {
        conv_layer1_out_V_ce1 = ap_const_logic_0;
    }
}

void nnet::thread_conv_layer1_out_V_d0() {
    conv_layer1_out_V_d0 = grp_conv_layer1_fu_519_output_V_d0.read();
}

void nnet::thread_conv_layer1_out_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        conv_layer1_out_V_we0 = grp_conv_layer1_fu_519_output_V_we0.read();
    } else {
        conv_layer1_out_V_we0 = ap_const_logic_0;
    }
}

void nnet::thread_conv_layer2_out_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        conv_layer2_out_V_address0 = grp_conv_layer2_fu_437_output_V_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        conv_layer2_out_V_address0 = grp_pool_layer2_fu_429_image_V_address0.read();
    } else {
        conv_layer2_out_V_address0 =  (sc_lv<12>) ("XXXXXXXXXXXX");
    }
}

void nnet::thread_conv_layer2_out_V_address1() {
    conv_layer2_out_V_address1 = grp_pool_layer2_fu_429_image_V_address1.read();
}

void nnet::thread_conv_layer2_out_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        conv_layer2_out_V_ce0 = grp_conv_layer2_fu_437_output_V_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        conv_layer2_out_V_ce0 = grp_pool_layer2_fu_429_image_V_ce0.read();
    } else {
        conv_layer2_out_V_ce0 = ap_const_logic_0;
    }
}

void nnet::thread_conv_layer2_out_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        conv_layer2_out_V_ce1 = grp_pool_layer2_fu_429_image_V_ce1.read();
    } else {
        conv_layer2_out_V_ce1 = ap_const_logic_0;
    }
}

void nnet::thread_conv_layer2_out_V_d0() {
    conv_layer2_out_V_d0 = grp_conv_layer2_fu_437_output_V_d0.read();
}

void nnet::thread_conv_layer2_out_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        conv_layer2_out_V_we0 = grp_conv_layer2_fu_437_output_V_we0.read();
    } else {
        conv_layer2_out_V_we0 = ap_const_logic_0;
    }
}

void nnet::thread_exitcond5_i_fu_805_p2() {
    exitcond5_i_fu_805_p2 = (!i_i1_reg_394.read().is_01() || !ap_const_lv4_A.is_01())? sc_lv<1>(): sc_lv<1>(i_i1_reg_394.read() == ap_const_lv4_A);
}

void nnet::thread_exitcond6_i_fu_695_p2() {
    exitcond6_i_fu_695_p2 = (!i_i7_reg_348.read().is_01() || !ap_const_lv7_54.is_01())? sc_lv<1>(): sc_lv<1>(i_i7_reg_348.read() == ap_const_lv7_54);
}

void nnet::thread_exitcond7_i_fu_561_p2() {
    exitcond7_i_fu_561_p2 = (!i_i_reg_313.read().is_01() || !ap_const_lv7_78.is_01())? sc_lv<1>(): sc_lv<1>(i_i_reg_313.read() == ap_const_lv7_78);
}

void nnet::thread_exitcond_i1_fu_716_p2() {
    exitcond_i1_fu_716_p2 = (!j_i1_reg_372.read().is_01() || !ap_const_lv7_78.is_01())? sc_lv<1>(): sc_lv<1>(j_i1_reg_372.read() == ap_const_lv7_78);
}

void nnet::thread_exitcond_i2_fu_826_p2() {
    exitcond_i2_fu_826_p2 = (!j_i2_reg_418.read().is_01() || !ap_const_lv7_54.is_01())? sc_lv<1>(): sc_lv<1>(j_i2_reg_418.read() == ap_const_lv7_54);
}

void nnet::thread_exitcond_i_fu_582_p2() {
    exitcond_i_fu_582_p2 = (!j_i_reg_337.read().is_01() || !ap_const_lv10_240.is_01())? sc_lv<1>(): sc_lv<1>(j_i_reg_337.read() == ap_const_lv10_240);
}

void nnet::thread_fc_layer1_out_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        fc_layer1_out_V_address0 =  (sc_lv<7>) (tmp_i1_fu_728_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()))) {
        fc_layer1_out_V_address0 = fc_layer1_out_V_addr_reg_970.read();
    } else {
        fc_layer1_out_V_address0 =  (sc_lv<7>) ("XXXXXXX");
    }
}

void nnet::thread_fc_layer1_out_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()))) {
        fc_layer1_out_V_ce0 = ap_const_logic_1;
    } else {
        fc_layer1_out_V_ce0 = ap_const_logic_0;
    }
}

void nnet::thread_fc_layer1_out_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        fc_layer1_out_V_d0 = a_V_i_i_cast_fu_690_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        fc_layer1_out_V_d0 = p_Val2_s_reg_324.read();
    } else {
        fc_layer1_out_V_d0 =  (sc_lv<24>) ("XXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void nnet::thread_fc_layer1_out_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()))) {
        fc_layer1_out_V_we0 = ap_const_logic_1;
    } else {
        fc_layer1_out_V_we0 = ap_const_logic_0;
    }
}

void nnet::thread_fc_layer1_weights_V_address0() {
    fc_layer1_weights_V_address0 =  (sc_lv<17>) (tmp_3_cast_fu_634_p1.read());
}

void nnet::thread_fc_layer1_weights_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        fc_layer1_weights_V_ce0 = ap_const_logic_1;
    } else {
        fc_layer1_weights_V_ce0 = ap_const_logic_0;
    }
}

void nnet::thread_fc_layer2_out_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        fc_layer2_out_V_address0 =  (sc_lv<7>) (tmp_i2_fu_838_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
        fc_layer2_out_V_address0 = fc_layer2_out_V_addr_reg_1026.read();
    } else {
        fc_layer2_out_V_address0 =  (sc_lv<7>) ("XXXXXXX");
    }
}

void nnet::thread_fc_layer2_out_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
        fc_layer2_out_V_ce0 = ap_const_logic_1;
    } else {
        fc_layer2_out_V_ce0 = ap_const_logic_0;
    }
}

void nnet::thread_fc_layer2_out_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read())) {
        fc_layer2_out_V_d0 = a_V_i_i1_cast_fu_800_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        fc_layer2_out_V_d0 = p_Val2_3_reg_359.read();
    } else {
        fc_layer2_out_V_d0 =  (sc_lv<24>) ("XXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void nnet::thread_fc_layer2_out_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state20.read()))) {
        fc_layer2_out_V_we0 = ap_const_logic_1;
    } else {
        fc_layer2_out_V_we0 = ap_const_logic_0;
    }
}

void nnet::thread_fc_layer2_weights_V_address0() {
    fc_layer2_weights_V_address0 =  (sc_lv<14>) (tmp_5_cast_fu_744_p1.read());
}

void nnet::thread_fc_layer2_weights_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        fc_layer2_weights_V_ce0 = ap_const_logic_1;
    } else {
        fc_layer2_weights_V_ce0 = ap_const_logic_0;
    }
}

void nnet::thread_fc_layer3_out_V_address0() {
    fc_layer3_out_V_address0 = fc_layer3_out_V_addr_reg_1087.read();
}

void nnet::thread_fc_layer3_out_V_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()))) {
        fc_layer3_out_V_ce0 = ap_const_logic_1;
    } else {
        fc_layer3_out_V_ce0 = ap_const_logic_0;
    }
}

void nnet::thread_fc_layer3_out_V_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read())) {
        fc_layer3_out_V_d0 = a_V_i_i2_cast_fu_940_p1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        fc_layer3_out_V_d0 = p_Val2_6_reg_405.read();
    } else {
        fc_layer3_out_V_d0 =  (sc_lv<24>) ("XXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void nnet::thread_fc_layer3_out_V_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state26.read()))) {
        fc_layer3_out_V_we0 = ap_const_logic_1;
    } else {
        fc_layer3_out_V_we0 = ap_const_logic_0;
    }
}

void nnet::thread_fc_layer3_weights_V_address0() {
    fc_layer3_weights_V_address0 =  (sc_lv<10>) (tmp_9_cast_fu_878_p1.read());
}

void nnet::thread_fc_layer3_weights_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read())) {
        fc_layer3_weights_V_ce0 = ap_const_logic_1;
    } else {
        fc_layer3_weights_V_ce0 = ap_const_logic_0;
    }
}

void nnet::thread_grp_conv_layer1_fu_519_ap_start() {
    grp_conv_layer1_fu_519_ap_start = ap_reg_grp_conv_layer1_fu_519_ap_start.read();
}

void nnet::thread_grp_conv_layer2_fu_437_ap_start() {
    grp_conv_layer2_fu_437_ap_start = ap_reg_grp_conv_layer2_fu_437_ap_start.read();
}

void nnet::thread_grp_pool_layer1_fu_511_ap_start() {
    grp_pool_layer1_fu_511_ap_start = ap_reg_grp_pool_layer1_fu_511_ap_start.read();
}

void nnet::thread_grp_pool_layer2_fu_429_ap_start() {
    grp_pool_layer2_fu_429_ap_start = ap_reg_grp_pool_layer2_fu_429_ap_start.read();
}

void nnet::thread_i_3_fu_701_p2() {
    i_3_fu_701_p2 = (!i_i7_reg_348.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(i_i7_reg_348.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void nnet::thread_i_4_fu_811_p2() {
    i_4_fu_811_p2 = (!i_i1_reg_394.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(i_i1_reg_394.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void nnet::thread_i_fu_567_p2() {
    i_fu_567_p2 = (!i_i_reg_313.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(i_i_reg_313.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void nnet::thread_j_3_fu_722_p2() {
    j_3_fu_722_p2 = (!j_i1_reg_372.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(j_i1_reg_372.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void nnet::thread_j_4_fu_832_p2() {
    j_4_fu_832_p2 = (!j_i2_reg_418.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(j_i2_reg_418.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void nnet::thread_j_fu_588_p2() {
    j_fu_588_p2 = (!j_i_reg_337.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(j_i_reg_337.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void nnet::thread_next_mul_fu_733_p2() {
    next_mul_fu_733_p2 = (!phi_mul_reg_383.read().is_01() || !ap_const_lv14_54.is_01())? sc_lv<14>(): (sc_biguint<14>(phi_mul_reg_383.read()) + sc_biguint<14>(ap_const_lv14_54));
}

void nnet::thread_p_Val2_2_fu_656_p2() {
    p_Val2_2_fu_656_p2 = (!tmp_18_i_cast_fu_653_p1.read().is_01() || !tmp_17_i_fu_645_p3.read().is_01())? sc_lv<44>(): (sc_bigint<44>(tmp_18_i_cast_fu_653_p1.read()) + sc_biguint<44>(tmp_17_i_fu_645_p3.read()));
}

void nnet::thread_p_Val2_5_fu_766_p2() {
    p_Val2_5_fu_766_p2 = (!tmp_13_i_cast_fu_763_p1.read().is_01() || !tmp_12_i_fu_755_p3.read().is_01())? sc_lv<44>(): (sc_bigint<44>(tmp_13_i_cast_fu_763_p1.read()) + sc_biguint<44>(tmp_12_i_fu_755_p3.read()));
}

void nnet::thread_p_Val2_7_fu_889_p0() {
    p_Val2_7_fu_889_p0 = fc_layer2_out_V_load_reg_1115.read();
}

void nnet::thread_p_Val2_7_fu_889_p1() {
    p_Val2_7_fu_889_p1 = fc_layer3_weights_V_1_reg_1110.read();
}

void nnet::thread_p_Val2_7_fu_889_p2() {
    p_Val2_7_fu_889_p2 = (!p_Val2_7_fu_889_p0.read().is_01() || !p_Val2_7_fu_889_p1.read().is_01())? sc_lv<43>(): sc_bigint<24>(p_Val2_7_fu_889_p0.read()) * sc_bigint<20>(p_Val2_7_fu_889_p1.read());
}

void nnet::thread_p_Val2_8_fu_906_p2() {
    p_Val2_8_fu_906_p2 = (!tmp_8_i_cast_fu_903_p1.read().is_01() || !tmp_7_i_fu_895_p3.read().is_01())? sc_lv<44>(): (sc_bigint<44>(tmp_8_i_cast_fu_903_p1.read()) + sc_biguint<44>(tmp_7_i_fu_895_p3.read()));
}

void nnet::thread_p_shl1_cast_fu_619_p1() {
    p_shl1_cast_fu_619_p1 = esl_zext<18,13>(tmp_1_fu_611_p3.read());
}

void nnet::thread_p_shl2_cast_fu_851_p1() {
    p_shl2_cast_fu_851_p1 = esl_zext<11,10>(tmp_6_fu_843_p3.read());
}

void nnet::thread_p_shl3_cast_fu_863_p1() {
    p_shl3_cast_fu_863_p1 = esl_zext<11,8>(tmp_7_fu_855_p3.read());
}

void nnet::thread_p_shl_cast_fu_607_p1() {
    p_shl_cast_fu_607_p1 = esl_zext<18,17>(tmp_fu_599_p3.read());
}

void nnet::thread_pool_layer1_out_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        pool_layer1_out_V_address0 = grp_pool_layer1_fu_511_output_V_address0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        pool_layer1_out_V_address0 = grp_conv_layer2_fu_437_image_V_address0.read();
    } else {
        pool_layer1_out_V_address0 =  (sc_lv<11>) ("XXXXXXXXXXX");
    }
}

void nnet::thread_pool_layer1_out_V_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        pool_layer1_out_V_address1 = grp_pool_layer1_fu_511_output_V_address1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        pool_layer1_out_V_address1 = grp_conv_layer2_fu_437_image_V_address1.read();
    } else {
        pool_layer1_out_V_address1 =  (sc_lv<11>) ("XXXXXXXXXXX");
    }
}

void nnet::thread_pool_layer1_out_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        pool_layer1_out_V_ce0 = grp_pool_layer1_fu_511_output_V_ce0.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        pool_layer1_out_V_ce0 = grp_conv_layer2_fu_437_image_V_ce0.read();
    } else {
        pool_layer1_out_V_ce0 = ap_const_logic_0;
    }
}

void nnet::thread_pool_layer1_out_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        pool_layer1_out_V_ce1 = grp_pool_layer1_fu_511_output_V_ce1.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        pool_layer1_out_V_ce1 = grp_conv_layer2_fu_437_image_V_ce1.read();
    } else {
        pool_layer1_out_V_ce1 = ap_const_logic_0;
    }
}

void nnet::thread_pool_layer1_out_V_d0() {
    pool_layer1_out_V_d0 = grp_pool_layer1_fu_511_output_V_d0.read();
}

void nnet::thread_pool_layer1_out_V_d1() {
    pool_layer1_out_V_d1 = grp_pool_layer1_fu_511_output_V_d1.read();
}

void nnet::thread_pool_layer1_out_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        pool_layer1_out_V_we0 = grp_pool_layer1_fu_511_output_V_we0.read();
    } else {
        pool_layer1_out_V_we0 = ap_const_logic_0;
    }
}

void nnet::thread_pool_layer1_out_V_we1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        pool_layer1_out_V_we1 = grp_pool_layer1_fu_511_output_V_we1.read();
    } else {
        pool_layer1_out_V_we1 = ap_const_logic_0;
    }
}

void nnet::thread_pool_layer2_out_V_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        pool_layer2_out_V_address0 =  (sc_lv<10>) (tmp_i_21_fu_594_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        pool_layer2_out_V_address0 = grp_pool_layer2_fu_429_output_V_address0.read();
    } else {
        pool_layer2_out_V_address0 =  (sc_lv<10>) ("XXXXXXXXXX");
    }
}

void nnet::thread_pool_layer2_out_V_address1() {
    pool_layer2_out_V_address1 = grp_pool_layer2_fu_429_output_V_address1.read();
}

void nnet::thread_pool_layer2_out_V_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        pool_layer2_out_V_ce0 = ap_const_logic_1;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        pool_layer2_out_V_ce0 = grp_pool_layer2_fu_429_output_V_ce0.read();
    } else {
        pool_layer2_out_V_ce0 = ap_const_logic_0;
    }
}

void nnet::thread_pool_layer2_out_V_ce1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        pool_layer2_out_V_ce1 = grp_pool_layer2_fu_429_output_V_ce1.read();
    } else {
        pool_layer2_out_V_ce1 = ap_const_logic_0;
    }
}

void nnet::thread_pool_layer2_out_V_d0() {
    pool_layer2_out_V_d0 = grp_pool_layer2_fu_429_output_V_d0.read();
}

void nnet::thread_pool_layer2_out_V_d1() {
    pool_layer2_out_V_d1 = grp_pool_layer2_fu_429_output_V_d1.read();
}

void nnet::thread_pool_layer2_out_V_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        pool_layer2_out_V_we0 = grp_pool_layer2_fu_429_output_V_we0.read();
    } else {
        pool_layer2_out_V_we0 = ap_const_logic_0;
    }
}

void nnet::thread_pool_layer2_out_V_we1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        pool_layer2_out_V_we1 = grp_pool_layer2_fu_429_output_V_we1.read();
    } else {
        pool_layer2_out_V_we1 = ap_const_logic_0;
    }
}

void nnet::thread_tmp_10_fu_782_p1() {
    tmp_10_fu_782_p1 = p_Val2_3_reg_359.read().range(23-1, 0);
}

void nnet::thread_tmp_11_fu_922_p1() {
    tmp_11_fu_922_p1 = p_Val2_6_reg_405.read().range(23-1, 0);
}

void nnet::thread_tmp_12_i_fu_755_p3() {
    tmp_12_i_fu_755_p3 = esl_concat<24,20>(p_Val2_3_reg_359.read(), ap_const_lv20_0);
}

void nnet::thread_tmp_13_i_cast_fu_763_p1() {
    tmp_13_i_cast_fu_763_p1 = esl_sext<44,42>(p_Val2_4_reg_1064.read());
}

void nnet::thread_tmp_17_i_fu_645_p3() {
    tmp_17_i_fu_645_p3 = esl_concat<24,20>(p_Val2_s_reg_324.read(), ap_const_lv20_0);
}

void nnet::thread_tmp_18_i_cast_fu_653_p1() {
    tmp_18_i_cast_fu_653_p1 = esl_sext<44,41>(p_Val2_1_reg_1003.read());
}

void nnet::thread_tmp_1_fu_611_p3() {
    tmp_1_fu_611_p3 = esl_concat<10,3>(j_i_reg_337.read(), ap_const_lv3_0);
}

void nnet::thread_tmp_2_fu_623_p2() {
    tmp_2_fu_623_p2 = (!p_shl_cast_fu_607_p1.read().is_01() || !p_shl1_cast_fu_619_p1.read().is_01())? sc_lv<18>(): (sc_biguint<18>(p_shl_cast_fu_607_p1.read()) - sc_biguint<18>(p_shl1_cast_fu_619_p1.read()));
}

void nnet::thread_tmp_3_cast_fu_634_p1() {
    tmp_3_cast_fu_634_p1 = esl_sext<64,18>(tmp_3_fu_629_p2.read());
}

void nnet::thread_tmp_3_fu_629_p2() {
    tmp_3_fu_629_p2 = (!tmp_2_fu_623_p2.read().is_01() || !tmp_i_cast_reg_965.read().is_01())? sc_lv<18>(): (sc_biguint<18>(tmp_2_fu_623_p2.read()) + sc_biguint<18>(tmp_i_cast_reg_965.read()));
}

void nnet::thread_tmp_4_fu_672_p1() {
    tmp_4_fu_672_p1 = p_Val2_s_reg_324.read().range(23-1, 0);
}

void nnet::thread_tmp_5_cast_fu_744_p1() {
    tmp_5_cast_fu_744_p1 = esl_zext<64,14>(tmp_5_fu_739_p2.read());
}

void nnet::thread_tmp_5_fu_739_p2() {
    tmp_5_fu_739_p2 = (!phi_mul_reg_383.read().is_01() || !tmp_i9_cast_reg_1021.read().is_01())? sc_lv<14>(): (sc_biguint<14>(phi_mul_reg_383.read()) + sc_biguint<14>(tmp_i9_cast_reg_1021.read()));
}

void nnet::thread_tmp_6_fu_843_p3() {
    tmp_6_fu_843_p3 = esl_concat<7,3>(j_i2_reg_418.read(), ap_const_lv3_0);
}

void nnet::thread_tmp_7_fu_855_p3() {
    tmp_7_fu_855_p3 = esl_concat<7,1>(j_i2_reg_418.read(), ap_const_lv1_0);
}

void nnet::thread_tmp_7_i_fu_895_p3() {
    tmp_7_i_fu_895_p3 = esl_concat<24,20>(p_Val2_6_reg_405.read(), ap_const_lv20_0);
}

void nnet::thread_tmp_8_fu_867_p2() {
    tmp_8_fu_867_p2 = (!p_shl3_cast_fu_863_p1.read().is_01() || !p_shl2_cast_fu_851_p1.read().is_01())? sc_lv<11>(): (sc_biguint<11>(p_shl3_cast_fu_863_p1.read()) + sc_biguint<11>(p_shl2_cast_fu_851_p1.read()));
}

void nnet::thread_tmp_8_i_cast_fu_903_p1() {
    tmp_8_i_cast_fu_903_p1 = esl_sext<44,43>(p_Val2_7_reg_1120.read());
}

void nnet::thread_tmp_9_cast_fu_878_p1() {
    tmp_9_cast_fu_878_p1 = esl_zext<64,11>(tmp_9_fu_873_p2.read());
}

void nnet::thread_tmp_9_fu_873_p2() {
    tmp_9_fu_873_p2 = (!tmp_8_fu_867_p2.read().is_01() || !tmp_i1_cast_reg_1082.read().is_01())? sc_lv<11>(): (sc_biguint<11>(tmp_8_fu_867_p2.read()) + sc_biguint<11>(tmp_i1_cast_reg_1082.read()));
}

void nnet::thread_tmp_fu_599_p3() {
    tmp_fu_599_p3 = esl_concat<10,7>(j_i_reg_337.read(), ap_const_lv7_0);
}

void nnet::thread_tmp_i1_27_fu_817_p1() {
    tmp_i1_27_fu_817_p1 = esl_zext<64,4>(i_i1_reg_394.read());
}

void nnet::thread_tmp_i1_cast_fu_822_p1() {
    tmp_i1_cast_fu_822_p1 = esl_zext<11,4>(i_i1_reg_394.read());
}

void nnet::thread_tmp_i1_fu_728_p1() {
    tmp_i1_fu_728_p1 = esl_zext<64,7>(j_i1_reg_372.read());
}

void nnet::thread_tmp_i2_fu_838_p1() {
    tmp_i2_fu_838_p1 = esl_zext<64,7>(j_i2_reg_418.read());
}

void nnet::thread_tmp_i9_cast_fu_712_p1() {
    tmp_i9_cast_fu_712_p1 = esl_zext<14,7>(i_i7_reg_348.read());
}

void nnet::thread_tmp_i9_fu_707_p1() {
    tmp_i9_fu_707_p1 = esl_zext<64,7>(i_i7_reg_348.read());
}

void nnet::thread_tmp_i_21_fu_594_p1() {
    tmp_i_21_fu_594_p1 = esl_zext<64,10>(j_i_reg_337.read());
}

void nnet::thread_tmp_i_cast_fu_578_p1() {
    tmp_i_cast_fu_578_p1 = esl_zext<18,7>(i_i_reg_313.read());
}

void nnet::thread_tmp_i_fu_573_p1() {
    tmp_i_fu_573_p1 = esl_zext<64,7>(i_i_reg_313.read());
}

void nnet::thread_tmp_i_i1_fu_786_p2() {
    tmp_i_i1_fu_786_p2 = (!p_Val2_3_reg_359.read().is_01() || !ap_const_lv24_0.is_01())? sc_lv<1>(): (sc_bigint<24>(p_Val2_3_reg_359.read()) > sc_bigint<24>(ap_const_lv24_0));
}

void nnet::thread_tmp_i_i2_fu_926_p2() {
    tmp_i_i2_fu_926_p2 = (!p_Val2_6_reg_405.read().is_01() || !ap_const_lv24_0.is_01())? sc_lv<1>(): (sc_bigint<24>(p_Val2_6_reg_405.read()) > sc_bigint<24>(ap_const_lv24_0));
}

void nnet::thread_tmp_i_i_fu_676_p2() {
    tmp_i_i_fu_676_p2 = (!p_Val2_s_reg_324.read().is_01() || !ap_const_lv24_0.is_01())? sc_lv<1>(): (sc_bigint<24>(p_Val2_s_reg_324.read()) > sc_bigint<24>(ap_const_lv24_0));
}

void nnet::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(grp_conv_layer1_fu_519_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(grp_pool_layer1_fu_511_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(grp_conv_layer2_fu_437_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(grp_pool_layer2_fu_429_ap_done.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(exitcond7_i_fu_561_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state15;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 512 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(exitcond_i_fu_582_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state14;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 16384 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && esl_seteq<1,1,1>(exitcond6_i_fu_695_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state21;
            } else {
                ap_NS_fsm = ap_ST_fsm_state16;
            }
            break;
        case 32768 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()) && esl_seteq<1,1,1>(exitcond_i1_fu_716_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state20;
            } else {
                ap_NS_fsm = ap_ST_fsm_state17;
            }
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 1048576 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state21.read()) && esl_seteq<1,1,1>(exitcond5_i_fu_805_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state22;
            }
            break;
        case 2097152 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state22.read()) && esl_seteq<1,1,1>(exitcond_i2_fu_826_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state26;
            } else {
                ap_NS_fsm = ap_ST_fsm_state23;
            }
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<26>) ("XXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void nnet::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"conv_layer1_out_V_address0\" :  \"" << conv_layer1_out_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"conv_layer1_out_V_ce0\" :  \"" << conv_layer1_out_V_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"conv_layer1_out_V_we0\" :  \"" << conv_layer1_out_V_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"conv_layer1_out_V_d0\" :  \"" << conv_layer1_out_V_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"conv_layer1_out_V_q0\" :  \"" << conv_layer1_out_V_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"conv_layer1_out_V_address1\" :  \"" << conv_layer1_out_V_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"conv_layer1_out_V_ce1\" :  \"" << conv_layer1_out_V_ce1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"conv_layer1_out_V_q1\" :  \"" << conv_layer1_out_V_q1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"conv_layer2_out_V_address0\" :  \"" << conv_layer2_out_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"conv_layer2_out_V_ce0\" :  \"" << conv_layer2_out_V_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"conv_layer2_out_V_we0\" :  \"" << conv_layer2_out_V_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"conv_layer2_out_V_d0\" :  \"" << conv_layer2_out_V_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"conv_layer2_out_V_q0\" :  \"" << conv_layer2_out_V_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"conv_layer2_out_V_address1\" :  \"" << conv_layer2_out_V_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"conv_layer2_out_V_ce1\" :  \"" << conv_layer2_out_V_ce1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"conv_layer2_out_V_q1\" :  \"" << conv_layer2_out_V_q1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"pool_layer1_out_V_address0\" :  \"" << pool_layer1_out_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"pool_layer1_out_V_ce0\" :  \"" << pool_layer1_out_V_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"pool_layer1_out_V_we0\" :  \"" << pool_layer1_out_V_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"pool_layer1_out_V_d0\" :  \"" << pool_layer1_out_V_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"pool_layer1_out_V_q0\" :  \"" << pool_layer1_out_V_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"pool_layer1_out_V_address1\" :  \"" << pool_layer1_out_V_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"pool_layer1_out_V_ce1\" :  \"" << pool_layer1_out_V_ce1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"pool_layer1_out_V_we1\" :  \"" << pool_layer1_out_V_we1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"pool_layer1_out_V_d1\" :  \"" << pool_layer1_out_V_d1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"pool_layer1_out_V_q1\" :  \"" << pool_layer1_out_V_q1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"pool_layer2_out_V_address0\" :  \"" << pool_layer2_out_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"pool_layer2_out_V_ce0\" :  \"" << pool_layer2_out_V_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"pool_layer2_out_V_we0\" :  \"" << pool_layer2_out_V_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"pool_layer2_out_V_d0\" :  \"" << pool_layer2_out_V_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"pool_layer2_out_V_q0\" :  \"" << pool_layer2_out_V_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"pool_layer2_out_V_address1\" :  \"" << pool_layer2_out_V_address1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"pool_layer2_out_V_ce1\" :  \"" << pool_layer2_out_V_ce1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"pool_layer2_out_V_we1\" :  \"" << pool_layer2_out_V_we1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"pool_layer2_out_V_d1\" :  \"" << pool_layer2_out_V_d1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"fc_layer1_out_V_address0\" :  \"" << fc_layer1_out_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"fc_layer1_out_V_ce0\" :  \"" << fc_layer1_out_V_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"fc_layer1_out_V_we0\" :  \"" << fc_layer1_out_V_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"fc_layer1_out_V_d0\" :  \"" << fc_layer1_out_V_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"fc_layer1_out_V_q0\" :  \"" << fc_layer1_out_V_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"fc_layer2_out_V_address0\" :  \"" << fc_layer2_out_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"fc_layer2_out_V_ce0\" :  \"" << fc_layer2_out_V_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"fc_layer2_out_V_we0\" :  \"" << fc_layer2_out_V_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"fc_layer2_out_V_d0\" :  \"" << fc_layer2_out_V_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"fc_layer2_out_V_q0\" :  \"" << fc_layer2_out_V_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"fc_layer3_out_V_address0\" :  \"" << fc_layer3_out_V_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"fc_layer3_out_V_ce0\" :  \"" << fc_layer3_out_V_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"fc_layer3_out_V_we0\" :  \"" << fc_layer3_out_V_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"fc_layer3_out_V_d0\" :  \"" << fc_layer3_out_V_d0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

