// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _conv_HH_
#define _conv_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "conv_fadd_32ns_32bkb.h"
#include "conv_fmul_32ns_32cud.h"
#include "conv_fcmp_32ns_32dEe.h"

namespace ap_rtl {

struct conv : public sc_module {
    // Port declarations 19
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<13> > output_r_address0;
    sc_out< sc_logic > output_r_ce0;
    sc_out< sc_logic > output_r_we0;
    sc_out< sc_lv<32> > output_r_d0;
    sc_out< sc_lv<10> > image_r_address0;
    sc_out< sc_logic > image_r_ce0;
    sc_in< sc_lv<32> > image_r_q0;
    sc_out< sc_lv<7> > weight_address0;
    sc_out< sc_logic > weight_ce0;
    sc_in< sc_lv<32> > weight_q0;
    sc_out< sc_lv<3> > bias_address0;
    sc_out< sc_logic > bias_ce0;
    sc_in< sc_lv<32> > bias_q0;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<32> > ap_var_for_const1;
    sc_signal< sc_lv<5> > ap_var_for_const2;


    // Module declarations
    conv(sc_module_name name);
    SC_HAS_PROCESS(conv);

    ~conv();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    conv_fadd_32ns_32bkb<1,5,32,32,32>* conv_fadd_32ns_32bkb_U1;
    conv_fmul_32ns_32cud<1,4,32,32,32>* conv_fmul_32ns_32cud_U2;
    conv_fcmp_32ns_32dEe<1,1,32,32,1>* conv_fcmp_32ns_32dEe_U3;
    sc_signal< sc_lv<24> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<4> > filter_1_fu_229_p2;
    sc_signal< sc_lv<4> > filter_1_reg_455;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<9> > tmp_cast1_fu_240_p1;
    sc_signal< sc_lv<9> > tmp_cast1_reg_460;
    sc_signal< sc_lv<1> > exitcond5_fu_223_p2;
    sc_signal< sc_lv<14> > tmp_cast_fu_244_p1;
    sc_signal< sc_lv<14> > tmp_cast_reg_465;
    sc_signal< sc_lv<3> > bias_addr_reg_470;
    sc_signal< sc_lv<10> > next_mul_fu_248_p2;
    sc_signal< sc_lv<10> > next_mul_reg_475;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<5> > i_1_fu_260_p2;
    sc_signal< sc_lv<5> > i_1_reg_483;
    sc_signal< sc_lv<5> > j_1_fu_272_p2;
    sc_signal< sc_lv<5> > j_1_reg_491;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<3> > row_offset_1_fu_288_p2;
    sc_signal< sc_lv<3> > row_offset_1_reg_499;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<5> > tmp_9_fu_294_p2;
    sc_signal< sc_lv<5> > tmp_9_reg_504;
    sc_signal< sc_lv<1> > exitcond2_fu_282_p2;
    sc_signal< sc_lv<6> > tmp_17_cast_fu_308_p1;
    sc_signal< sc_lv<6> > tmp_17_cast_reg_509;
    sc_signal< sc_lv<14> > tmp_10_fu_334_p2;
    sc_signal< sc_lv<14> > tmp_10_reg_514;
    sc_signal< sc_lv<3> > col_offset_1_fu_349_p2;
    sc_signal< sc_lv<3> > col_offset_1_reg_522;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<1> > exitcond1_fu_343_p2;
    sc_signal< sc_lv<32> > image_load_reg_537;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<32> > weight_load_reg_542;
    sc_signal< sc_lv<32> > grp_fu_214_p2;
    sc_signal< sc_lv<32> > tmp_5_reg_547;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<32> > grp_fu_208_p2;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_lv<32> > bias_load_reg_557;
    sc_signal< sc_logic > ap_CS_fsm_state17;
    sc_signal< sc_lv<32> > a_assign_reg_562;
    sc_signal< sc_logic > ap_CS_fsm_state22;
    sc_signal< sc_lv<32> > a_assign_1_fu_441_p3;
    sc_signal< sc_lv<32> > a_assign_1_reg_569;
    sc_signal< sc_logic > ap_CS_fsm_state23;
    sc_signal< sc_lv<4> > filter_reg_115;
    sc_signal< sc_lv<1> > exitcond4_fu_254_p2;
    sc_signal< sc_lv<5> > i_reg_126;
    sc_signal< sc_lv<1> > exitcond3_fu_266_p2;
    sc_signal< sc_lv<10> > phi_mul_reg_138;
    sc_signal< sc_lv<5> > j_reg_150;
    sc_signal< sc_logic > ap_CS_fsm_state24;
    sc_signal< sc_lv<32> > sum_reg_162;
    sc_signal< sc_lv<3> > row_offset_reg_174;
    sc_signal< sc_lv<32> > sum_1_reg_185;
    sc_signal< sc_lv<3> > col_offset_reg_197;
    sc_signal< sc_lv<64> > tmp_fu_235_p1;
    sc_signal< sc_lv<64> > tmp_13_fu_368_p1;
    sc_signal< sc_lv<64> > tmp_23_cast_fu_395_p1;
    sc_signal< sc_lv<64> > tmp_15_cast_fu_448_p1;
    sc_signal< sc_lv<32> > grp_fu_208_p0;
    sc_signal< sc_lv<32> > grp_fu_208_p1;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_logic > ap_CS_fsm_state18;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<5> > row_offset_cast4_fu_278_p1;
    sc_signal< sc_lv<5> > tmp_11_fu_300_p3;
    sc_signal< sc_lv<10> > tmp_7_cast_fu_312_p1;
    sc_signal< sc_lv<10> > tmp_7_fu_316_p2;
    sc_signal< sc_lv<13> > tmp_8_fu_322_p3;
    sc_signal< sc_lv<14> > tmp_14_cast_fu_330_p1;
    sc_signal< sc_lv<5> > col_offset_cast2_fu_339_p1;
    sc_signal< sc_lv<5> > tmp_2_fu_355_p2;
    sc_signal< sc_lv<10> > tmp_12_fu_361_p3;
    sc_signal< sc_lv<6> > tmp_8_cast_fu_373_p1;
    sc_signal< sc_lv<6> > tmp_14_fu_377_p2;
    sc_signal< sc_lv<9> > tmp_22_cast_fu_382_p3;
    sc_signal< sc_lv<9> > tmp_15_fu_390_p2;
    sc_signal< sc_lv<32> > a_assign_to_int_fu_400_p1;
    sc_signal< sc_lv<8> > tmp_6_fu_403_p4;
    sc_signal< sc_lv<23> > tmp_1_fu_413_p1;
    sc_signal< sc_lv<1> > notrhs_fu_423_p2;
    sc_signal< sc_lv<1> > notlhs_fu_417_p2;
    sc_signal< sc_lv<1> > tmp_4_fu_429_p2;
    sc_signal< sc_lv<1> > tmp_s_fu_218_p2;
    sc_signal< sc_lv<1> > tmp_3_fu_435_p2;
    sc_signal< sc_lv<24> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<24> ap_ST_fsm_state1;
    static const sc_lv<24> ap_ST_fsm_state2;
    static const sc_lv<24> ap_ST_fsm_state3;
    static const sc_lv<24> ap_ST_fsm_state4;
    static const sc_lv<24> ap_ST_fsm_state5;
    static const sc_lv<24> ap_ST_fsm_state6;
    static const sc_lv<24> ap_ST_fsm_state7;
    static const sc_lv<24> ap_ST_fsm_state8;
    static const sc_lv<24> ap_ST_fsm_state9;
    static const sc_lv<24> ap_ST_fsm_state10;
    static const sc_lv<24> ap_ST_fsm_state11;
    static const sc_lv<24> ap_ST_fsm_state12;
    static const sc_lv<24> ap_ST_fsm_state13;
    static const sc_lv<24> ap_ST_fsm_state14;
    static const sc_lv<24> ap_ST_fsm_state15;
    static const sc_lv<24> ap_ST_fsm_state16;
    static const sc_lv<24> ap_ST_fsm_state17;
    static const sc_lv<24> ap_ST_fsm_state18;
    static const sc_lv<24> ap_ST_fsm_state19;
    static const sc_lv<24> ap_ST_fsm_state20;
    static const sc_lv<24> ap_ST_fsm_state21;
    static const sc_lv<24> ap_ST_fsm_state22;
    static const sc_lv<24> ap_ST_fsm_state23;
    static const sc_lv<24> ap_ST_fsm_state24;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<10> ap_const_lv10_0;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<10> ap_const_lv10_1D;
    static const sc_lv<5> ap_const_lv5_1D;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<3> ap_const_lv3_4;
    static const sc_lv<3> ap_const_lv3_1;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<8> ap_const_lv8_FF;
    static const sc_lv<23> ap_const_lv23_0;
    static const sc_lv<5> ap_const_lv5_2;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_var_for_const2();
    void thread_ap_clk_no_reset_();
    void thread_a_assign_1_fu_441_p3();
    void thread_a_assign_to_int_fu_400_p1();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state18();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state22();
    void thread_ap_CS_fsm_state23();
    void thread_ap_CS_fsm_state24();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_bias_address0();
    void thread_bias_ce0();
    void thread_col_offset_1_fu_349_p2();
    void thread_col_offset_cast2_fu_339_p1();
    void thread_exitcond1_fu_343_p2();
    void thread_exitcond2_fu_282_p2();
    void thread_exitcond3_fu_266_p2();
    void thread_exitcond4_fu_254_p2();
    void thread_exitcond5_fu_223_p2();
    void thread_filter_1_fu_229_p2();
    void thread_grp_fu_208_p0();
    void thread_grp_fu_208_p1();
    void thread_i_1_fu_260_p2();
    void thread_image_r_address0();
    void thread_image_r_ce0();
    void thread_j_1_fu_272_p2();
    void thread_next_mul_fu_248_p2();
    void thread_notlhs_fu_417_p2();
    void thread_notrhs_fu_423_p2();
    void thread_output_r_address0();
    void thread_output_r_ce0();
    void thread_output_r_d0();
    void thread_output_r_we0();
    void thread_row_offset_1_fu_288_p2();
    void thread_row_offset_cast4_fu_278_p1();
    void thread_tmp_10_fu_334_p2();
    void thread_tmp_11_fu_300_p3();
    void thread_tmp_12_fu_361_p3();
    void thread_tmp_13_fu_368_p1();
    void thread_tmp_14_cast_fu_330_p1();
    void thread_tmp_14_fu_377_p2();
    void thread_tmp_15_cast_fu_448_p1();
    void thread_tmp_15_fu_390_p2();
    void thread_tmp_17_cast_fu_308_p1();
    void thread_tmp_1_fu_413_p1();
    void thread_tmp_22_cast_fu_382_p3();
    void thread_tmp_23_cast_fu_395_p1();
    void thread_tmp_2_fu_355_p2();
    void thread_tmp_3_fu_435_p2();
    void thread_tmp_4_fu_429_p2();
    void thread_tmp_6_fu_403_p4();
    void thread_tmp_7_cast_fu_312_p1();
    void thread_tmp_7_fu_316_p2();
    void thread_tmp_8_cast_fu_373_p1();
    void thread_tmp_8_fu_322_p3();
    void thread_tmp_9_fu_294_p2();
    void thread_tmp_cast1_fu_240_p1();
    void thread_tmp_cast_fu_244_p1();
    void thread_tmp_fu_235_p1();
    void thread_weight_address0();
    void thread_weight_ce0();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
