lappend pragmaStatus0 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "conv/conv_label0" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "conv/conv_label1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus2 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "conv/conv_label2" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "conv/conv_label3" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "conv/conv_label4" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "STREAM" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "main" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'STREAM' cannot be applied: Function 'main' does not exist in any synthesis source file." variable "in"}
lappend pragmaStatus6 {pragma "STREAM" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "main" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'STREAM' cannot be applied: Function 'main' does not exist in any synthesis source file." variable "out"}
lappend pragmaStatus7 {pragma "STREAM" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "conv" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "out"}
lappend pragmaStatus8 {pragma "STREAM" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "conv" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "in"}
lappend pragmaStatus9 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "conv/conv_label0" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus10 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "conv/conv_label1" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus11 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "conv/conv_label2" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus12 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "conv/conv_label3" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus13 {pragma "UNROLL" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "conv/conv_label4" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus14 {pragma "PIPELINE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "conv/conv_label5" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus15 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_cos_K1' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "second_order_float::sin_cos_K1"}
lappend pragmaStatus16 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_K2' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::sin_K2"}
lappend pragmaStatus17 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::cos_K1' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::cos_K1"}
lappend pragmaStatus18 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::cos_K0' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::cos_K0"}
lappend pragmaStatus19 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'first_order_fixed_16::sin_cos_K0' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "first_order_fixed_16::sin_cos_K0"}
lappend pragmaStatus20 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_cos_K2' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "second_order_float::sin_cos_K2"}
lappend pragmaStatus21 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::cos_K3' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::cos_K3"}
lappend pragmaStatus22 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_K1' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::sin_K1"}
lappend pragmaStatus23 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_cos_K4' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "fourth_order_double::sin_cos_K4"}
lappend pragmaStatus24 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_cos_K2' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "fourth_order_double::sin_cos_K2"}
lappend pragmaStatus25 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_cos_K0' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "fourth_order_double::sin_cos_K0"}
lappend pragmaStatus26 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_cos_K1' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "fourth_order_double::sin_cos_K1"}
lappend pragmaStatus27 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::cos_K4' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::cos_K4"}
lappend pragmaStatus28 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_K0' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::sin_K0"}
lappend pragmaStatus29 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_K0' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::sin_K0"}
lappend pragmaStatus30 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::cos_K2' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::cos_K2"}
lappend pragmaStatus31 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_cos_K0' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "second_order_float::sin_cos_K0"}
lappend pragmaStatus32 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_cos_K3' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "fourth_order_double::sin_cos_K3"}
lappend pragmaStatus33 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_K2' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::sin_K2"}
lappend pragmaStatus34 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_K3' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::sin_K3"}
lappend pragmaStatus35 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::sin_K4' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::sin_K4"}
lappend pragmaStatus36 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::cos_K1' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::cos_K1"}
lappend pragmaStatus37 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'second_order_float::sin_K1' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "second_order_float::sin_K1"}
lappend pragmaStatus38 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "sin_or_cos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'first_order_fixed_16::sin_cos_K1' can not be recognized(UNKNOWN VARIABLE) in 'sin_or_cos_approximation'." variable "first_order_fixed_16::sin_cos_K1"}
lappend pragmaStatus39 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::cos_K0' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::cos_K0"}
lappend pragmaStatus40 {pragma "RESOURCE" source "/home/sergiu/git/lic/hls/workspace/conv/solution1/conv.cpp" location "sincos_approximation" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'RESOURCE' for core 'ROM_1P_LUTRAM' cannot be applied: Variable 'fourth_order_double::cos_K2' can not be recognized(UNKNOWN VARIABLE) in 'sincos_approximation'." variable "fourth_order_double::cos_K2"}
