// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4.1
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __conv_layer2_conv_DeQ_H__
#define __conv_layer2_conv_DeQ_H__


#include <systemc>
using namespace sc_core;
using namespace sc_dt;




#include <iostream>
#include <fstream>

struct conv_layer2_conv_DeQ_ram : public sc_core::sc_module {

  static const unsigned DataWidth = 19;
  static const unsigned AddressRange = 16;
  static const unsigned AddressWidth = 4;

//latency = 1
//input_reg = 1
//output_reg = 0
sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in <sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


sc_lv<DataWidth> ram[AddressRange];


   SC_CTOR(conv_layer2_conv_DeQ_ram) {
        ram[0] = "0b0000000011101001110";
        ram[1] = "0b0110001001000110101";
        ram[2] = "0b1110000101000001001";
        ram[3] = "0b0011111111000010101";
        ram[4] = "0b0110011111100000100";
        ram[5] = "0b1110011110100010111";
        ram[6] = "0b1101000010000111101";
        ram[7] = "0b0010010001011100101";
        ram[8] = "0b0111011111111101101";
        ram[9] = "0b1100110001000001111";
        ram[10] = "0b1000111100110011101";
        ram[11] = "0b0110101100101111000";
        ram[12] = "0b1100011101001100010";
        ram[13] = "0b1010001101000001010";
        ram[14] = "0b0000001111101001011";
        ram[15] = "0b0110111101011010100";


SC_METHOD(prc_write_0);
  sensitive<<clk.pos();
   }


void prc_write_0()
{
    if (ce0.read() == sc_dt::Log_1) 
    {
            if(address0.read().is_01() && address0.read().to_uint()<AddressRange)
              q0 = ram[address0.read().to_uint()];
            else
              q0 = sc_lv<DataWidth>();
    }
}


}; //endmodule


SC_MODULE(conv_layer2_conv_DeQ) {


static const unsigned DataWidth = 19;
static const unsigned AddressRange = 16;
static const unsigned AddressWidth = 4;

sc_core::sc_in <sc_lv<AddressWidth> > address0;
sc_core::sc_in<sc_logic> ce0;
sc_core::sc_out <sc_lv<DataWidth> > q0;
sc_core::sc_in<sc_logic> reset;
sc_core::sc_in<bool> clk;


conv_layer2_conv_DeQ_ram* meminst;


SC_CTOR(conv_layer2_conv_DeQ) {
meminst = new conv_layer2_conv_DeQ_ram("conv_layer2_conv_DeQ_ram");
meminst->address0(address0);
meminst->ce0(ce0);
meminst->q0(q0);

meminst->reset(reset);
meminst->clk(clk);
}
~conv_layer2_conv_DeQ() {
    delete meminst;
}


};//endmodule
#endif
